[[fblangref-security-user]]
= Управление пользователями

В данном разделе описываются операторы создания, модификации и удаления учётных записей пользователей Firebird средствами операторов SQL.
Такая возможность предоставлена следующим пользователям:

* `SYSDBA`;
* Любому пользователю, имеющему права на роль `RDB$ADMIN` в базе данных пользователей и права на ту же роль для базы данных в активном подключении. Пользователь должен подключаться к базе данных с ролью `RDB$ADMIN` или получить её права, если роль назначена в качестве роли по умолчанию;
* Любому пользователю с ролью, которой назначена системная привилегия USER_MANAGEMENT в базе данных безопасности. Пользователь должен подключаться к базе данных с этой ролью или получить её права, если роль назначена в качестве роли по умолчанию;
* При включенном флаге AUTO ADMIN MAPPING в базе данных пользователей ([path]_security4.fdb_ или той, что установлена для вашей базы данных в файле [path]_databases.conf_) -- любой администратор операционной системы Windows (при условии использования сервером доверенной авторизации -- trusted authentication) без указания роли. При этом не важно, включен или выключен флаг `AUTO ADMIN MAPPING` в самой базе данных.

Непривилегированные пользователи могут использовать только оператор `ALTER USER` для изменения собственной учётной записи.

[[fblangref-security-user-create]]
== `CREATE USER`

.Назначение
Создание учётной записи пользователя Firebird.
(((CREATE USER)))

.Доступно в
DSQL

.Синтаксис
[listing,subs=+quotes]
----
CREATE USER _username_
  PASSWORD '_password_'
  [<user_option> [<user_option> ...]]
  [TAGS ( <tag> [, <tag>  ...] )]

<user_option> ::=
    FIRSTNAME '_firstname_'
  | MIDDLENAME '_middlename_'
  | LASTNAME '_lastname_'
  | {ACTIVE | INACTIVE}
  | USING PLUGIN _pluginname_
  | GRANT ADMIN ROLE

<tag> ::=
  _tagname_ = '_string_value_'
----

[[fblangref-security-tbl-createuser]]
.Параметры оператора `CREATE USER`
[cols="<1,<3", options="header",stripes="none"]
|===
^| Параметр
^| Описание

|username
|Имя пользователя.
Максимальная длина 63 символов.

|[password
|Пароль пользователя.
Чувствительно к регистру.

|firstname
|Вспомогательная информация: имя пользователя.
Максимальная длина 32 символа.

|middlename
|Вспомогательная информация: "второе имя" (отчество, "имя отца") пользователя.
Максимальная длина 32 символа.

|lastname
|Вспомогательная информация: фамилия пользователя.
Максимальная длина 32 символа.

|pluginname
|Имя плагина управления пользователями, в котором необходимо создать нового пользователя.

|tagname
|Имя пользовательского атрибута.
Максимальная длина 63 символа.
Имя атрибута должно подчиняться правилам наименования SQL идентификаторов.

|string_value
|Значение пользовательского атрибута.
Максимальная длина 255 символов.
|===

Оператор `CREATE USER` создаёт учётную запись пользователя Firebird.
Пользователь должен отсутствовать в текущей базе данных безопасности Firebird иначе будет выдано соответствующее сообщение об ошибке.

[IMPORTANT]
====
Начиная с Firebird 3.0 имена пользователей подчиняются общему правилу наименования идентификаторов объектов метаданных.
Таким образом, пользователь с именем `"Alex"` и с именем `"ALEX"` будут разными пользователями.

[source,sql]
----
CREATE USER ALEX PASSWORD 'bz23ds';

-- этот пользователь такой же как и первый
CREATE USER Alex PASSWORD 'bz23ds';

-- этот пользователь такой же как и первый
CREATE USER "ALEX" PASSWORD 'bz23ds';

-- а это уже другой пользователь
CREATE USER "Alex" PASSWORD 'bz23ds';
----
====

(((CREATE USER, PASSWORD)))
Предложение `PASSWORD` задаёт пароль пользователя.
Максимальная длина пароля зависит от того какой плагин управления пользователями задействован (параметр [parameter]``UserManager``).
Для плагина SRP эффективная длина пароля ограничена 20 байтами *. Плагин Legacy_UserManager максимальная длина пароля равна 8 байт.

.*Почему эффективная длина пароля ограничена 20 символами?
[NOTE]
====
На длину пароля нет ограничения в 20 байт и он может быть использован.
Хеши различных паролей, длина которых более 20 байт, тоже различны.
Предел эффективности наступает из-за ограниченной длины хеша в SHA1 равном 20 байт или 160 бит.
Рано или поздно найдётся более короткий пароль с тем же хешем с помощью атаки Brute Force.
Именно поэтому часто говорят, что эффективная длина пароля для алгоритма SHA1 составляет 20 байт.
====

Необязательные предложения `FIRSTNAME`, `MIDDLENAME` и `LASTNAME` задают дополнительные атрибуты пользователя, такие как имя пользователя (имя человека), отчество и фамилия соответственно.

(((CREATE USER, ACTIVE))) (((CREATE USER, INACTIVE)))
Если при создании учётной записи будет указан атрибут `INACTIVE`, то пользователь будет создан в "`неактивном состоянии`", т.е.
подключиться с его учётной записью будет невозможно.
При указании атрибута `ACTIVE` пользователь будет создан в активном состоянии.
По умолчанию пользователь создаётся активным.
Данная возможность доступна только при использовании Srp в качестве менеджера пользователей.

(((CREATE USER, GRANT ADMIN ROLE)))
Если указана опция `GRANT ADMIN ROLE`, то новая учётная запись пользователя создаётся с правами роли `RDB$ADMIN` в текущей базе данных безопасности.
Это позволяет вновь созданному пользователю управлять учётными записями пользователей, но не даёт ему специальных полномочий в обычных базах данных.

(((CREATE USER, USING PLUGIN)))
Необязательное предложение `USING PLUGIN` позволяет явно указывать какой плагин управления пользователями будет использован.
По умолчанию используется тот плагин, который был указан первым в списке параметра [parameter]``UserManager`` в файле конфигурации [path]_firebird.conf_.
Допустимыми являются только значения, перечисленные в параметре [parameter]``UserManager``.

.Важно
[IMPORTANT]
====
Учтите что одноименные пользователи, созданные с помощью разных плагинов управления пользователями -- это разные пользователи.
Поэтому пользователя созданного с помощью одного плагина управления пользователями можно удалить или изменить, указав только тот же самый плагин.
====

(((CREATE USER, TAGS)))
Кроме того вы можете задать неограниченное количество пользовательских атрибутов с помощью необязательного предложения `TAGS`.
Данная возможность доступна только при использовании Srp в качестве менеджера пользователей.

[[fblangref-security-user-createpriv]]
=== Кто может создать пользователя

* `SYSDBA` и другие пользователи являющиеся администраторами в базе данных безопасности (с ролью `RDB$ADMIN`);
* Пользователи вошедшие с ролью или получившие её привилегии (роль назначена по умолчанию), которой назначена системная привилегия `USER_MANAGEMENT`.


[[fblangref-security-user-create-exmpl]]
=== Примеры `CREATE USER`

.Создание пользователя
[example]
====
[source,sql]
----
CREATE USER bigshot PASSWORD 'buckshot';
----
====

.Создание пользователя с помощью плагина управления пользователями `Legacy_UserManager`
[example]
====
[source,sql]
----
CREATE USER godzilla PASSWORD 'robot'
USING PLUGIN Legacy_UserManager;
----
====

.Создание пользователя с пользовательскими атрибутами.
[example]
====
[source,sql]
----
CREATE USER john PASSWORD 'fYe_3Ksw'
FIRSTNAME 'John'
LASTNAME 'Doe'
TAGS (BIRTHYEAR = '1970', CITY = 'New York');
----
====

.Создание пользователя в неактивном состоянии.
[example]
====
[source,sql]
----
CREATE USER john PASSWORD 'fYe_3Ksw'
FIRSTNAME 'John'
LASTNAME 'Doe'
INACTIVE;
----
====

.Создание пользователя с возможностью управления пользователями
[example]
====
[source,sql]
----
CREATE USER superuser PASSWORD 'kMn8Kjh'
GRANT ADMIN ROLE;
----
====

.См. также:
<<fblangref-security-user-alter>>, <<fblangref-security-user-createoralter>>, <<fblangref-security-user-drop>>.

[[fblangref-security-user-alter]]
== `ALTER USER`

.Назначение:
Изменение учётной записи пользователя Firebird.
(((ALTER USER)))

.Доступно в:
DSQL.

.Синтаксис:
[listing,subs=+quotes]
----
ALTER {USER _username_ | CURRENT USER}
  [SET] [<user_option> [<user_option> ...]]
  [USING PLUGIN _pluginname_]
  [{GRANT | REVOKE} ADMIN ROLE]
  [TAGS ( <tag> [, <tag>  ...] )]

<user_option> ::=
    PASSWORD '_password_'
  | FIRSTNAME '_firstname_'
  | MIDDLENAME '_middlename_'
  | LASTNAME '_lastname_'
  | {ACTIVE | INACTIVE}

<tag> ::=
    _tagname_ = '_string_value_'
  | DROP _tagname_
----

Описание параметров оператора смотри в <<fblangref-security-user-create>>.

Оператор `ALTER USER` изменяет данные учётной записи пользователя.
В операторе `ALTER USER` должно присутствовать хотя бы одно из необязательных предложений.

(((ALTER USER, PASSWORD)))
Необязательное предложение `PASSWORD` задаёт новый пароль пользователя.

Необязательные предложения `FIRSTNAME`, `MIDDLENAME` и `LASTNAME` позволяют изменить дополнительные атрибуты пользователя, такие как имя пользователя (имя человека), отчество и фамилия соответственно.

(((ALTER USER, ACTIVE))) (((ALTER USER, INACTIVE)))
Атрибут `INACTIVE` позволяет сделать учётную запись неактивной.
Это удобно когда необходимо временно отключить учётную запись без её удаления.
Атрибут `ACTIVE` позволяет вернуть неактивную учётную запись в активное состояние.
Данная возможность доступна только при использовании `Srp` в качестве менеджера пользователей.

(((ALTER USER, TAGS)))
Необязательное предложение `TAGS` позволяет задать, изменить или удалить пользовательские атрибуты.
Если в списке атрибутов, атрибута с заданным именем не было, то он будет добавлен, иначе его значение будет изменено.
Атрибуты не указанные в списке не будут изменены.
Для удаления пользовательского атрибута перед его именем в списке атрибутов необходимо указать ключевое слово DROP.
Данная возможность доступна только при использовании `Srp` в качестве менеджера пользователей.

(((ALTER USER, GRANT ADMIN ROLE)))
Предложение `GRANT ADMIN ROLE` предоставляет указанному пользователю привилегии роли `RDB$ADMIN` в текущей базе данных безопасности.
Это позволяет указанному пользователю управлять учётными записями пользователей, но не даёт ему специальных полномочий в обычных базах данных.

(((ALTER USER, REVOKE ADMIN ROLE)))
Предложение `REVOKE ADMIN ROLE` отбирает у указанного пользователя привилегии роли `RDB$ADMIN` в текущей базе данных безопасности.
Это запрещает указанному пользователю управлять учётными записями пользователей.

(((ALTER USER, USING PLUGIN)))
Необязательное предложение `USING PLUGIN` позволяет явно указывать какой плагин управления пользователями будет использован.
По умолчанию используется тот плагин, который был указан первым в списке параметра [parameter]``UserManager`` в файле конфигурации [path]_firebird.conf_.
Допустимыми являются только значения, перечисленные в параметре [parameter]``UserManager``.

.Важно:
[IMPORTANT]
====
Учтите что одноименные пользователи, созданные с помощью разных плагинов управления пользователями -- это разные пользователи.
Поэтому пользователя созданного с помощью одного плагина управления пользователями можно удалить или изменить, указав только тот же самый плагин.
====

Если требуется изменить свою учётную запись, то вместо указания имени текущего пользователя можно использовать ключевое слово `CURRENT USER`.

[[fblangref-security-user-alter-who]]
=== Кто может модифицировать учётную пользователя?

Модифицировать чужую учётную запись могут:

* `SYSDBA` и другие пользователи являющиеся администраторами в базе данных безопасности (с ролью `RDB$ADMIN`);
* Пользователи вошедшие с ролью или получившие её привилегии (роль назначена по умолчанию), которой назначена системная привилегия `USER_MANAGEMENT`.

Свои собственные учётные записи могут изменять любые пользователи, однако это не относится к опциям `{GRANT | REVOKE} ADMIN ROLE` и атрибуту `ACTIVE`/`INACTIVE` для изменения которых необходимы административные привилегии.

[[fblangref-security-user-alter-exmpl]]
=== Примеры `ALTER USER`

.Изменение пользователя и выдача ему привилегии управления пользователями.
[example]
====
[source,sql]
----
ALTER USER bobby PASSWORD '67-UiT_G8'
GRANT ADMIN ROLE;
----
====

.Изменение пароля пользователя, созданного с помощью плагина управления пользователями `Legacy_UserManager`.
[example]
====
[source,sql]
----
ALTER USER godzilla PASSWORD 'robot12'
USING PLUGIN Legacy_UserManager;
----
====

.Изменение дополнительных атрибутов своей учётной записи.
[example]
====
[source,sql]
----
ALTER CURRENT USER
FIRSTNAME 'No_Jack'
LASTNAME 'Kennedy';
----
====

.Отключение учётной записи пользователя.
[example]
====
[source,sql]
----
ALTER USER dan INACTIVE;
----
====

.Отбор привилегии управления пользователями у пользователя.
[example]
====
[source,sql]
----
ALTER USER dumbbell
REVOKE ADMIN ROLE;
----
====

.Изменение пользовательских атрибутов своей учётной записи.
[example]
====
[source,sql]
----
ALTER CURRENT USER
TAGS (BIRTHYEAR = '1971', DROP CITY);
----

Атрибуту `BIRTHDAY` будет установлено новое значение, а атрибут `CITY` будет удалён.
====

.См. также:
<<fblangref-security-user-create>>, <<fblangref-security-user-createoralter>>, <<fblangref-security-user-drop>>.

[[fblangref-security-user-createoralter]]
== `CREATE OR ALTER USER`

.Назначение
Создание или изменение учётной записи пользователя Firebird.
(((CREATE OR ALTER USER)))

.Доступно в
DSQL

.Синтаксис
[source]
----
ALTER USER _username_
  [SET] [<user_option> [<user_option> ...]]
  [USING PLUGIN _pluginname_]
  [{GRANT | REVOKE} ADMIN ROLE]
  [TAGS ( <tag> [, <tag>  ...] )]

<user_option> ::=
    PASSWORD '_password_'
  | FIRSTNAME '_firstname_'
  | MIDDLENAME '_middlename_'
  | LASTNAME '_lastname_'
  | {ACTIVE | INACTIVE}

<tag> ::=
    _tagname_ = '_string_value_'
  | DROP _tagname_
----

Описание параметров оператора смотри в <<fblangref-security-user-create>>.

Оператор `CREATE OR ALTER USER` создаёт новую или изменяет учётную запись.
Если пользователя не существует, то он будет создан с использованием предложения `CREATE USER`.
Если он уже существует, то он будет изменён, при этом существующие привилегии сохраняются.

[[fblangref-security-user-createoralter-exmpl]]
=== Примеры `CREATE OR ALTER USER`

.Создание или изменение пользователя.
[example]
====
[source,sql]
----
CREATE OR ALTER USER john
PASSWORD 'fYe_3Ksw'
FIRSTNAME 'John'
LASTNAME 'Doe'
INACTIVE;
----
====

.См. также:
<<fblangref-security-user-create>>, <<fblangref-security-user-alter>>.

[[fblangref-security-user-drop]]
== `DROP USER`

.Назначение
Удаление учётной записи пользователя Firebird
(((DROP USER)))

.Доступно в
DSQL

.Синтаксис
[listing,subs=+quotes]
----
DROP USER _username_
  [USING PLUGIN _pluginname_]
----

[[fblangref-security-tbl-dropuser]]
.Параметры оператора `DROP USER`
[cols="<1,<3", options="header",stripes="none"]
|===
^| Параметр
^| Описание

|username
|Имя пользователя.

|pluginname
|Имя плагина управления пользователями, в котором был создан данный пользователь.
|===

Оператор `DROP USER` удаляет учётную запись пользователя Firebird.

(((DROP USER, USING PLUGIN)))
Необязательное предложение `USING PLUGIN` позволяет явно указывать какой плагин управления пользователями будет использован.
По умолчанию используется тот плагин, который был указан первым в списке параметра [parameter]``UserManager`` в файле конфигурации [path]_firebird.conf_.
Допустимыми являются только значения, перечисленные в параметре [parameter]``UserManager``.

[IMPORTANT]
====
Учтите что одноименные пользователи, созданные с помощью разных плагинов управления пользователями -- это разные пользователи.
Поэтому пользователя созданного с помощью одного плагина управления пользователями можно удалить или изменить, указав только тот же самый плагин.
====

[[fblangref-security-user-drop-who]]
=== Кто может удалить учётную запись пользователя?

* `SYSDBA` и другие пользователи являющиеся администраторами в базе данных безопасности (с ролью `RDB$ADMIN`);
* Пользователи вошедшие с ролью или получившие её привилегии (роль назначена по умолчанию), которой назначена системная привилегия `USER_MANAGEMENT`.

[[fblangref-security-user-drop-exmpl]]
=== Примеры `DROP USER`

.Удаление пользователя.
[example]
====
[source,sql]
----
DROP USER bobby;
----
====

.Удаление пользователя, созданного с помощью плагина управления пользователями `Legacy_UserManager`.
[example]
====
[source,sql]
----
DROP USER Godzilla USING PLUGIN Legacy_UserManager;
----
====

.См. также:
<<fblangref-security-user-create>>, <<fblangref-security-user-alter>>.

[[fblangref-security-user-recreate]]
== `RECREATE USER`

.Назначение
Создание новой учётной записи пользователя Firebird или пересоздание существующей.
(((RECREATE USER)))

.Доступно в
DSQL

.Синтаксис
[listing,subs=+quotes]
----
RECREATE USER _username_
  PASSWORD '_password_'
  [<user_option> [<user_option> ...]]
  [TAGS ( <tag> [, <tag>  ...] )]

<user_option> ::=
    FIRSTNAME '_firstname_'
  | MIDDLENAME '_middlename_'
  | LASTNAME '_lastname_'
  | {ACTIVE | INACTIVE}
  | USING PLUGIN _pluginname_
  | GRANT ADMIN ROLE

<tag> ::=
  _tagname_ = '_string_value_'
----

Описание параметров оператора смотри в <<fblangref-security-user-create>>.

Оператор `RECREATE USER` создаёт нового или пересоздаёт существующего пользователя.
Если пользователь с таким именем уже существует, то оператор `RECREATE TABLE` удалить его и создаст нового.
Существующие привилегии при этом будут сохранены.

[[fblangref-security-user-recreate-exmpl]]
=== Примеры `RECREATE USER`

.Создание или пересоздание пользователя.
[example]
====
[source,sql]
----
RECREATE USER john PASSWORD 'fYe_3Ksw'
FIRSTNAME 'John'
LASTNAME 'Doe'
INACTIVE;
----
====

.См. также:
<<fblangref-security-user-create>>, <<fblangref-security-user-drop>>.

[[fblangref-security-user-list]]
== Получение списка пользователей

Для получения списка пользователей и их атрибутов вы можете воспользоваться виртуальными таблицами `SEC$USERS` и `SEC$USER_ATTRIBUTES`.

.Отображение списка пользователей и их атрибутов
[example]
====
[source,sql]
----
SELECT
  CAST(U.SEC$USER_NAME AS CHAR(20)) AS LOGIN,
  CAST(A.SEC$KEY AS CHAR(10)) AS TAG,
  CAST(A.SEC$VALUE AS CHAR(20)) AS "VALUE",
  U.SEC$PLUGIN AS "PLUGIN"
FROM SEC$USERS U
  LEFT JOIN SEC$USER_ATTRIBUTES A
         ON U.SEC$USER_NAME = A.SEC$USER_NAME
        AND U.SEC$PLUGIN = A.SEC$PLUGIN;
----

[listing]
----
   LOGIN                TAG        VALUE                PLUGIN
   ==================== ========== ==================== ==========================
   SYSDBA               <null>     <null>               Srp
   ALEX                 B          x                    Srp
   ALEX                 C          sample               Srp
   SYSDBA               <null>     <null>               Legacy_UserManager
----
====

.Подробное описание виртуальных таблиц безопасности смотри в:
<<fblangref-sectables-users,SEC$USERS>>, <<fblangref-sectables-user_attributes,SEC$USER_ATTRIBUTES>>.
