
[[_fblangref_ddl_exception]]
= EXCEPTION

Пользовательское исключение (exception) -- объект базы данных, описывающий сообщение об ошибке.
Исключение можно вызывать и обрабатывать в PSQL коде (см. <<_fblangref_psql_statements_exception,EXCEPTION>>, <<_fblangref_psql_statements_when,WHEN ... DO>>).

В данном разделе описываются операторы создания, модификации и удаления исключений. 

[[_fblangref_ddl_exception_create]]
== CREATE EXCEPTION
(((CREATE EXCEPTION)))

.Назначение:
Создание пользовательского исключения для использования в PSQL модулях.

.Доступно в:
DSQL, ESQL.

.Синтаксис:

[source]
----

CREATE EXCEPTION exception_name '<message>';

<message> ::= {txt | @n} <message>
----



.Параметры оператора CREATE EXCEPTION
[cols="1,1", frame="all", options="header"]
|===
| Параметр
| Описание

|[replaceable]``exception_name``
|

Имя исключения.
Максимальная длина 63 символов.

|[replaceable]``message``
|

Сообщение об ошибке.
Максимальная длина ограничена 1021 символом.

|[replaceable]``txt``
|

Текст.

|[replaceable]``т``
|

Номер слота для параметра.
Нумерация начинается с 1.
Максимальный номер слота равен 9.
|===

Оператор CREATE EXCEPTION создаёт новое пользовательское исключение для использования в PSQL модулях.
Исключение должно отсутствовать в базе данных, иначе будет выдана соответствующая ошибка.

Имя исключения является стандартным идентификатором.
В диалекте 3 оно может быть заключено в двойные кавычки, что делает его чувствительным к регистру.
Подробности см. <<_fblangref_structure_identifiers,Идентификаторы>>.

Сообщение исключения сохраняется в наборе символов NONE, т.е.
любых символов из однобайтовых наборов символов.
Текст сообщения может быть переопределён в PSQL коде во время возбуждения исключения.

Сообщение об ошибке может содержать слоты для параметров, которые заполняются при возбуждении исключения. 

.Внимание!
[WARNING]
====
Если в тексте сообщения, встретится номер слота параметра больше 9, то второй и последующий символ будут восприняты как литералы.
Например, @10 будет воспринято как @1, после которого следует литерал 0. 
====

[NOTE]
====
Пользовательские исключения хранятся в таблице <<_fblangref_systables_exceptions,RDB$EXCEPTION>>.
====

[[_fblangref_ddl_exception_create_who]]
=== Кто может создать исключение?

Выполнить оператор `CREATE EXCEPTION` могут: 

* <<_fblangref_security_administrators,Администраторы>>
* Пользователи с привилегией ``CREATE EXCEPTION``. 

Пользователь, создавший исключение, становится его владельцем.

[[_fblangref_ddl_exception_create_examples]]
=== Примеры

.Создание пользовательского исключения
[example]

[source,sql]
----
 
CREATE EXCEPTION E_LARGE_VALUE 'Значение превышает предельно допустимое';
----

.Создание параметризованного исключения
[example]

[source,sql]
----
 
CREATE EXCEPTION E_INVALID_VALUE 
'Неверное значение @1 для поля @2';
----

.См. также:
<<_fblangref_ddl_exception_alter,ALTER EXCEPTION>>, <<_fblangref_ddl_exception_createoralter,CREATE OR ALTER
                        EXCEPTION>>, <<_fblangref_ddl_exception_drop,DROP
                        EXCEPTION>>, <<_fblangref_ddl_exception_recreate,RECREATE
                        EXCEPTION>>, <<_fblangref_psql_statements_exception,EXCEPTION>>. 

[[_fblangref_ddl_exception_alter]]
== ALTER EXCEPTION
(((ALTER EXCEPTION)))

.Назначение:
Изменение текста сообщения пользовательского исключения.

.Доступно в:
DSQL, ESQL.

.Синтаксис:

[source]
----

ALTER EXCEPTION exception_name '<message>';

<message> ::= {txt | @n} <message>
----



.Параметры оператора ALTER EXCEPTION
[cols="1,1", frame="all", options="header"]
|===
| Параметр
| Описание

|[replaceable]``exception_name``
|

Имя исключения.

|[replaceable]``message``
|

Сообщение об ошибке.
Максимальная длина ограничена 1021 символом.

|[replaceable]``txt``
|

Текст.

|[replaceable]``т``
|

Номер слота для параметра.
Нумерация начинается с 1.
Максимальный номер слота равен 9.
|===

Оператор ALTER EXCEPTION изменяет текст сообщения пользовательского исключения. 

[[_fblangref_ddl_exception_alter_who]]
=== Кто может изменить исключение?

Выполнить оператор `ALTER EXCEPTION` могут: 

* <<_fblangref_security_administrators,Администраторы>>
* Владелец исключения; 
* Пользователи с привилегией ``ALTER ANY EXCEPTION``. 


[[_fblangref_ddl_exception_alter_examples]]
=== Примеры

.Изменение текста сообщения пользовательского исключения
[example]

[source,sql]
----
 
ALTER EXCEPTION E_LARGE_VALUE 'Значение превышает максимально допустимое';
----

.См. также:
<<_fblangref_ddl_exception_create,CREATE EXCEPTION>>, <<_fblangref_ddl_exception_createoralter,CREATE OR ALTER
                        EXCEPTION>>, <<_fblangref_ddl_exception_recreate,RECREATE
                        EXCEPTION>>. 

[[_fblangref_ddl_exception_createoralter]]
== CREATE OR ALTER EXCEPTION
(((CREATE OR ALTER EXCEPTION)))

.Назначение:
Создание нового или изменение существующего исключения.

.Доступно в:
DSQL.

.Синтаксис:

[source]
----

CREATE OR ALTER EXCEPTION exception_name '<message>';

<message> ::= {txt | @n} <message>
----



.Параметры оператора CREATE OR ALTER EXCEPTION
[cols="1,1", frame="all", options="header"]
|===
| Параметр
| Описание

|[replaceable]``exception_name``
|

Имя исключения.
Максимальная длина 63 символов.

|[replaceable]``message``
|

Сообщение об ошибке.
Максимальная длина ограничена 1021 символом.

|[replaceable]``txt``
|

Текст.

|[replaceable]``т``
|

Номер слота для параметра.
Нумерация начинается с 1.
Максимальный номер слота равен 9.
|===

Если исключения не существует, то оно будет создано.
Уже существующее исключение будет изменено, при этом существующие зависимости исключения будут сохранены. 

[[_fblangref_ddl_exception_createoralter_examples]]
=== Примеры

.Создание или изменение пользовательского исключения
[example]

[source,sql]
----
 
CREATE OR ALTER EXCEPTION E_LARGE_VALUE 
'Значение превышает максимально допустимое';
----

.См. также:
<<_fblangref_ddl_exception_create,CREATE EXCEPTION>>, <<_fblangref_ddl_exception_alter,ALTER EXCEPTION>>, <<_fblangref_ddl_exception_recreate,RECREATE EXCEPTION>>. 

[[_fblangref_ddl_exception_drop]]
== DROP EXCEPTION
(((DROP EXCEPTION)))

.Назначение:
Удаление пользовательского исключения.

.Доступно в:
DSQL, ESQL.

.Синтаксис:

[source]
----

DROP EXCEPTION exception_name
----



.Параметры оператора DROP EXCEPTION
[cols="1,1", frame="all", options="header"]
|===
| Параметр
| Описание

|[replaceable]``exception_name``
|

Имя исключения.
|===

Оператор DROP EXCEPTION удаляет пользовательское исключение.
При наличии зависимостей для существующего исключения удаления не будет выполнено. 

[[_fblangref_ddl_exception_drop_who]]
=== Кто может удалить исключение?

Выполнить оператор `DROP EXCEPTION` могут: 

* <<_fblangref_security_administrators,Администраторы>>
* Владелец исключения; 
* Пользователи с привилегией ``DROP ANY EXCEPTION``. 


[[_fblangref_ddl_exception_drop_examples]]
=== Примеры

.Удаление пользовательского исключения
[example]

[source,sql]
----
 
DROP EXCEPTION E_LARGE_VALUE;
----

.См. также:
<<_fblangref_ddl_exception_create,CREATE EXCEPTION>>, <<_fblangref_ddl_exception_recreate,RECREATE EXCEPTION>>. 

[[_fblangref_ddl_exception_recreate]]
== RECREATE EXCEPTION
(((RECREATE EXCEPTION)))

.Назначение:
Создание или пересоздание пользовательского исключения.

.Доступно в:
DSQL.

.Синтаксис:

[source]
----

RECREATE EXCEPTION exception_name '<message>';

<message> ::= {txt | @n} <message>
----



.Параметры оператора RECREATE EXCEPTION
[cols="1,1", frame="all", options="header"]
|===
| Параметр
| Описание

|[replaceable]``exception_name``
|

Имя исключения.
Максимальная длина 63 символов.

|[replaceable]``message``
|

Сообщение об ошибке.
Максимальная длина ограничена 1021 символом.

|[replaceable]``txt``
|

Текст.

|[replaceable]``т``
|

Номер слота для параметра.
Нумерация начинается с 1.
Максимальный номер слота равен 9.
|===

Оператор RECREATE EXCEPTION создаёт или пересоздаёт пользовательское исключение.
Если исключение с таким именем уже существует, то оператор RECREATE EXCEPTION попытается удалить его и создать новое исключение.
При наличии зависимостей для существующего исключения оператор RECREATE EXCEPTION не выполнится. 

[[_fblangref_ddl_exception_recreate_examples]]
=== Примеры

.Создание или пересоздание пользовательского исключения
[example]

[source,sql]
----
 
RECREATE EXCEPTION E_LARGE_VALUE 
'Значение превышает максимально допустимое';
----

.См. также:
<<_fblangref_ddl_exception_create,CREATE EXCEPTION>>, <<_fblangref_ddl_exception_alter,ALTER EXCEPTION>>, <<_fblangref_ddl_exception_createoralter,CREATE OR ALTER
                        EXCEPTION>>. 

ifdef::backend-docbook[]
[index]
== Index
// Generated automatically by the DocBook toolchain.
endif::backend-docbook[]