[[fblangref-ddl-charset]]
= CHARACTER SET

[[fblangref-ddl-charset-alter]]
== `ALTER CHARACTER SET`

.Назначение
Установка сортировки по умолчанию для набора символов.
(((ALTER CHARACTER SET)))

.Доступно в
DSQL

.Синтаксис
[listing,subs="+quotes"]
----
ALTER CHARACTER SET _charset_
SET DEFAULT COLLATION _collation_
----

[[fblangref-ddl-tbl-charsetalter]]
.Параметры оператора `ALTER CHARACTER SET`
[cols="<1,<3", options="header",stripes="none"]
|===
^| Параметр
^| Описание

|charset
|Набор символов.

|collation
|Сортировка.
|===

Оператор `ALTER CHARACTER SET` изменяет сортировку по умолчанию для указанного набора символов.
Это повлияет на использование набора символов в будущем, кроме случаев, когда явно переопределена сортировка `COLLATE`.
Сортировка существующих доменов, столбцов и переменных PSQL при этом не будет изменена. 

[NOTE]
====
Если сортировка по умолчанию была изменена для набора символов базы данных (тот, что был указан при создании базы данных), то также изменяется и сортировка по умолчанию для базы данных. 

Если сортировка по умолчанию была изменена для набора символов, который был указан при подключении, то строковые константы будут интерпретироваться в соответствии с новыми параметрами сортировки (если набор символов и/или сортировка не переопределяются).
====

[[fblangref-ddl-charset-alter-examples]]
=== Примеры

.Установка сортировки UNICODE_CI_AI по умолчанию для кодировки UTF8
[example]
====
[source,sql]
----
ALTER CHARACTER SET UTF8 SET DEFAULT COLLATION UNICODE_CI_AI;
----
====
