[[fblangref-ddl-index]]
= INDEX

Индекс -- это объект базы данных, используемый для более быстрого извлечения данных из таблицы или для ускорения сортировки в запросе.
Кроме того, индексы используются для обеспечения ограничений целостности -- `PRIMARY KEY`, `FOREIGN KEY`, `UNIQUE`.

В данном разделе описываются вопросы создания индексов, перевода их в активное/неактивное состояние, удаление индексов и сбор статистики (пересчёт селективности) для индексов.

[[fblangref-ddl-index-create]]
== `CREATE INDEX`

.Назначение
Создание индекса для таблицы.
(((CREATE INDEX)))

.Доступно в
DSQL, ESQL.

[listing,subs=+quotes]
----
CREATE [UNIQUE] [ASC[ENDING] | DESC[ENDING]] 
INDEX _indexname_ ON _tablename_
{(_col_ [, _col_ ...]) | COMPUTED BY (<expression>)};
----

[[fblangref-ddl-idx-createidx]]
.Параметры оператора `CREATE INDEX`
[cols="<1,<3", options="header",stripes="none"]
|===
^| Параметр
^| Описание

|indexname
|Имя индекса.
Может содержать до 63 символов.

|tablename
|Имя таблицы, для которой строится индекс.

|col
|Столбец таблицы.
В качестве столбцов не могут быть использованы поля типа BLOB, ARRAY и вычисляемые поля.

|expression
|Выражение, содержащее столбцы таблицы.
|===

Оператор `CREATE INDEX` создаёт индекс для таблицы, который может быть использован для ускорения поиска, сортировки и/или группирования.
Кроме того, индекс может быть использован при определении ограничений, таких как первичный ключ, внешний ключ или ограничениях уникальности.
Индекс может быть построен на столбцах любого типа кроме `BLOB` и массивов.
Имя индекса должно быть уникальным среди всех имён индексов.

.Индексы в ключах
[NOTE]
====
При добавлении ограничений первичного ключа, внешнего ключа или ограничения уникальности будет неявно создан одноименный индекс.
Так, например, при выполнении следующего оператора будет неявно создан индекс PK_COUNTRY. 

[source,sql]
----
ALTER TABLE COUNTRY 
ADD CONSTRAINT PK_COUNTRY PRIMARY KEY (ID);
----
====

[[fblangref-ddl-index-unique]]
=== Уникальные индексы

(((CREATE INDEX, UNIQUE)))
Если при создании индекса указано ключевое слово `UNIQUE`, то индекс гарантирует уникальность значений ключей.
Такой индекс называется уникальным.
Уникальный индекс не является ограничением уникальности. 

Уникальные индексы не могут содержать дубликаты значений ключей (или дубликаты комбинаций значений ключей в случае составного, многоколоночного или многосегментного индекса). Дубликаты значения `NULL` допускаются в соответствии со стандартом SQL-99, в том числе и в многосегментном индексе.

[[fblangref-ddl-index-direction]]
=== Направление индекса

(((CREATE INDEX, ASCENDING))) (((CREATE INDEX, DESCENDING)))
Все индексы в Firebird являются однонаправленными.
Индекс может быть построен в восходящем и нисходящем порядке.
Ключевые слова `ASC[ENDING]` (сокращённо `ASC`) и `DESC[ENDING]` используются для указания направленности индекса.
По умолчанию создаётся восходящий `ASC[ENDING]` индекс.
Допускается одновременное определение восходящего и нисходящего индекса на одном и том же столбце или наборе ключей.

[TIP]
====
Убывающий (`DESC[ENDING]`) индекс может быть полезен при поиске наивысших значений (максимум, последнее и т.д.)
====

[[fblangref-ddl-index-computed]]
=== Вычисляемые индексы или индексы по выражению

(((CREATE INDEX, COMPUTED BY)))
При создании индекса вместо одного или нескольких столбцов вы также можете указать одно выражение, используя предложение `COMPUTED BY`.
Такой индекс называется вычисляемым или индексом по выражению.
Вычисляемые индексы используются в запросах, в которых условие в предложениях `WHERE`, `ORDER BY` или `GROUP BY` в точности совпадает с выражением в определении индекса.
Выражение в вычисляемом индексе может использовать несколько столбцов таблицы. 

[[fblangref-ddl-index-keylimits]]
=== Ограничения на индексы

Максимальная длина ключа индекса ограничена 1/4 размера страницы. 

[[fblangref-ddl-index-keylimits-char]]
==== Ограничения на длину индексируемой строки

Максимальная длина индексируемой строки на 9 байтов меньше, чем максимальная длина ключа.
Максимальная длина индексируемой строки зависит от размера страницы и набора символов.

[[fblangref-ddl-idx-idxstrnglgth]]
.Длина индексируемой строки и набор символов
[%autowidth,cols=">1,>1,>1,>1,>1,>1", stripes="none"]
|===
.2+^h|Размер страницы
5+^h|Максимальная длина индексируемой строки для набора символов, байт/символ

^h| 1
^h| 2
^h| 3
^h| 4
^h| 6

| 4096 
| 1015 
| 507 
| 338 
| 253 
| 169 

| 8192 
| 2039 
| 1019 
| 679 
| 509 
| 339 

| 16384 
| 4087 
| 2043 
| 1362 
| 1021 
| 681 

| 32768 
| 8183 
| 4091 
| 2727 
| 2045 
| 1363 
|===

[[fblangref-ddl-index-limitpertable]]
=== Максимальное количество индексов на таблицу

Для каждой таблицы максимально возможное количество индексов ограничено и зависит от размера страницы и количества столбцов в индексе.

[[fblangref-ddl-idx-idxpertbl]]
.Число индексов и количество столбцов
[%autowidth,cols=">1,>1,>1,>1",stripes="none"]
|===
.2+^h|  Размер страницы
3+^h|  Число индексов в зависимости от количества столбцов в индексе

|  1 
|  2 
|  3 

| 4096 
| 203 
| 145 
| 113 

| 8192 
| 408 
| 291 
| 227 

| 16384 
| 818 
| 584 
| 454 

|32768
|1637
|1169
|909
|===

[[fblangref-ddl-index-creat-_who]]
=== Кто может создать индекс?

Выполнить оператор `CREATE INDEX` могут: 

* <<fblangref-security-administrators,Администраторы>>
* Владелец таблицы, для которой создаётся индекс; 
* Пользователи с привилегией `ALTER ANY TABLE`.


[[fblangref-ddl-index-create-examples]]
=== Примеры

.Создание индекса
[example]
====
[source,sql]
----
CREATE INDEX IDX_UPDATER ON SALARY_HISTORY (UPDATER_ID);
----
====

.Создание индекса с сортировкой ключей по убыванию
[example]
====
[source,sql]
----
CREATE DESCENDING INDEX IDX_CHANGE 
ON SALARY_HISTORY (CHANGE_DATE);
----
====

.Создание многосегментного индекса
[example]
====
[source,sql]
----
CREATE INDEX IDX_SALESTAT ON SALES (ORDER_STATUS, PAID);
----
====

.Создание индекса, не допускающего дубликаты значений
[example]
====
[source,sql]
----
CREATE UNIQUE INDEX UNQ_COUNTRY_NAME ON COUNTRY (NAME);
----
====

.Создание вычисляемого индекса
[example]
====
[source,sql]
----
CREATE INDEX IDX_NAME_UPPER ON PERSONS 
COMPUTED BY (UPPER (NAME));
----

Такой индекс может быть использован для не чувствительного к регистру поиска.

[source,sql]
----
SELECT * 
FROM PERSONS 
WHERE UPPER(NAME) STARTING WITH UPPER('Iv');
----
====

.См. также:
<<fblangref-ddl-index-alter,ALTER INDEX>>, <<fblangref-ddl-index-drop,DROP INDEX>>.

[[fblangref-ddl-index-alter]]
== `ALTER INDEX`

.Назначение
Перевод индекса в активное/неактивное состояние, перестройка индекса.
(((ALTER INDEX)))

.Доступно в
DSQL, ESQL.

.Синтаксис
[listing,subs=+quotes]
----
ALTER INDEX _indexname_ {ACTIVE | INACTIVE};
----

[[fblangref-ddl-idx-alteridx]]
.Параметры оператора `ALTER INDEX`
[cols="<1,<3", options="header",stripes="none"]
|===
^| Параметр
^| Описание

|indexname
|Имя индекса.
|===

Оператор `ALTER INDEX` переводит индекс в активное/неактивное состояние.
Возможность изменения структуры и порядка сортировки ключей этот оператор не предусматривает.

`INACTIVE`::
(((ALTER INDEX, INACTIVE)))
При выборе опции `INACTIVE`, индекс переводится из активного в неактивное состояние. Перевод индекса в неактивное состояние по своему действию похоже на команду `DROP INDEX` за исключением того, что определение индекса сохраняется в базе данных. Невозможно перевести в неактивное состояние индекс участвующий в ограничении.
+
Активный индекс может быть отключен, только если отсутствуют запросы использующие этот индекс, иначе будет возвращена ошибка "`object in use`".
+
Активация неактивного индекс также безопасна.
Тем не менее, если есть активные транзакции, модифицирующие таблицу, то транзакция, содержащая оператор `ALTER INDEX` потерпит неудачу, если она имеет атрибут `NO WAIT`.
Если транзакция находится в режиме `WAIT`, то она будет ждать завершения параллельных транзакций.
+
С другой стороны, если наш оператор `ALTER INDEX` начинает перестраивать индекс на `COMMIT`, то другие транзакции, изменяющие эту таблицу, потерпят неудачу или будут ожидать в соответствии с их `WAIT`/`NO WAIT` атрибутами.
Та же самая ситуация будет и при выполнении `CREATE INDEX`.
+
[TIP]
====
Перевод индекса в неактивное состояние может быть полезен при массовой вставке, модификации или удалении записей из таблицы, для которой этот индекс построен. 
====

`ACTIVE`::
(((ALTER INDEX, ACTIVE)))
При выборе альтернативы `ACTIVE` индекс переводится из неактивного состояния в активное. При переводе индекса из неактивного состояния в активное -- индекс перестраивается.
+
[TIP]
====
Даже если индекс находится в активном состоянии оператор `ALTER INDEX ... ACTIVE` всё равно перестраивает индекс.
Таким образом, эту команду можно использовать как часть обслуживания БД для перестройки индексов, автоматически созданных для ограничений
`PRIMARY KEY`, `FOREIGN KEY`, `UNIQUE`, для которых выполнение оператора `ALTER INDEX ... INACTIVE` невозможно.
====

[[fblangref-ddl-index-alter-active-constr-use]]
=== Использование `ALTER INDEX` для индексов ограничений

Принудительный перевод индексов созданных для ограничений `PRIMARY KEY`, `FOREIGN KEY` и `UNIQUE` не допускается.
Тем не менее выполнение оператора `ALTER INDEX ... INACTIVE` работает так же хорошо для индексов ограничений, как и другие инструменты для других индексов.

[[fblangref-ddl-index-alter-who]]
=== Кто может выполнить `ALTER INDEX`?

Выполнить оператор `ALTER INDEX` могут: 

* <<fblangref-security-administrators,Администраторы>>
* Владелец таблицы, для которой построен индекс; 
* Пользователи с привилегией `ALTER ANY TABLE`.


[[fblangref-ddl-index-alter-examples]]
=== Примеры

.Перевод индекса в неактивное состояние
[example]
====
[source,sql]
----
ALTER INDEX IDX_UPDATER INACTIVE;
----
====

.Возврат индекса в активное состояние
[example]
====
[source,sql]
----
ALTER INDEX IDX_UPDATER ACTIVE;
----
====

.См. также:
<<fblangref-ddl-index-create,CREATE INDEX>>, <<fblangref-ddl-index-drop,DROP INDEX>>.

[[fblangref-ddl-index-drop]]
== `DROP INDEX`

.Назначение
Удаление индекса из базы данных.
(((DROP INDEX)))

.Доступно в
DSQL, ESQL.

.Синтаксис
[listing,subs=+quotes]
----
DROP INDEX _indexname_
----

.Параметры оператора `DROP INDEX`
[cols="<1,<3", options="header",stripes="none"]
|===
^| Параметр
^| Описание

|indexname
|Имя индекса.
|===

Оператор `DROP INDEX` удаляет существующий индекс из базы данных.
При наличии зависимостей для существующего индекса (если он используется в ограничении) удаление не будет выполнено.

[[fblangref-ddl-index-drop-who]]
=== Кто может удалить индекс?

Выполнить оператор `DROP INDEX` могут: 

* <<fblangref-security-administrators,Администраторы>>
* Владелец таблицы, для которой построен индекс; 
* Пользователи с привилегией `ALTER ANY TABLE`.


[[fblangref-ddl-index-drop-examples]]
=== Примеры

.Удаление индекса
[example]
====
[source,sql]
----
DROP INDEX IDX_UPDATER;
----
====

.См. также:
<<fblangref-ddl-index-create,CREATE INDEX>>, <<fblangref-ddl-index-alter,ALTER INDEX>>.

[[fblangref-ddl-index-stat]]
== `SET STATISTICS`

.Назначение
Пересчёт селективности индекса.
(((SET STATISTICS)))

.Доступно в
DSQL, ESQL.

.Синтаксис
[listing,subs=+quotes]
----
SET STATISTICS INDEX _indexname_
----

.Параметры оператора `SET STATISTICS`
[cols="<1,<3", options="header",stripes="none"]
|===
^| Параметр
^| Описание

|indexname
|Имя индекса.
|===

Оператор `SET STATISTICS` пересчитывает значение селективности для указанного индекса.

[[fblangref-ddl-index-selectivity]]
=== Селективность индекса

Селективность (избирательность) индекса -- это оценочное количество строк, которые могут быть выбраны при поиске по каждому значению индекса.
Уникальный индекс имеет максимальную селективность, поскольку при его использовании невозможно выбрать более одной строки для каждого значения ключа индекса.
Актуальность селективности индекса важна для выбора наиболее оптимального плана выполнения запросов оптимизатором.

Пересчёт селективности индекса может потребоваться после массовой вставки, модификации или удалении большого количества записей из таблицы, поскольку она становится неактуальной.

[NOTE]
====
Отметим, что в Firebird статистика индексов автоматически не пересчитывается ни после массовых изменений данных, ни при каких либо других условиях.
При создании (`CREATE`) или его активации (`ALTER INDEX ACTIVE`) статистика индекса полностью соответствует его содержимому.
====

Пересчёт селективности индекса может быть выполнен под высоко параллельной нагрузкой без риска его повреждения.
Тем не менее следует помнить, что при высоком параллелизме рассчитанная статистика может устареть, как только закончится выполнение оператора `SET STATISTICS`.

[[fblangref-ddl-index-stat_who]]
=== Кто может обновить статистику?

Выполнить оператор `SET STATISTICS` могут: 

* <<fblangref-security-administrators,Администраторы>>
* Владелец таблицы, для которой построен индекс; 
* Пользователи с привилегией `ALTER ANY TABLE`.


[[fblangref-ddl-index-stat-examples]]
=== Примеры

.Пересчёт селективности индекса IDX_UPDATER
[example]
====
[source,sql]
----
SET STATISTICS INDEX IDX_UPDATER;
----
====

.См. также:
<<fblangref-ddl-index-create,CREATE INDEX>>, <<fblangref-ddl-index-alter,ALTER INDEX>>.
