[[fblangref-ddl-sequence]]
= SEQUENCE (GENERATOR)

Последовательность (sequence) или генератор (generator) -- объект базы данных, предназначенный для получения уникального числового значения.
Термин последовательность является SQL совместимым.
Ранее в Interbase и Firebird последовательности называли генераторами.

Независимо от диалекта базы данных последовательности (или генераторы) всегда хранятся как 64-битные целые значения. 

[CAUTION]
====
Если клиент использует 1 диалект, то сервер передаёт ему значения последовательности, усечённые до 32-битного значения.
Если значение последовательности передаются в 32-разрядное поле или переменную, то до тех пор, пока текущее значение последовательности не вышло за границы для 32-битного числа, ошибок не будет.
В момент выхода значения последовательности за этот диапазон база данных 3-го диалекта выдаст сообщение об ошибке, а база данных 1-ого диалекта будет молча обрезать значения, что также может привести к ошибке -- например, если поле, заполняемое генератором, является первичным или уникальным.
====

В данном разделе описываются вопросы создания, модификации (установка значения последовательности) и удаления последовательностей.

[[fblangref-ddl-sequence-create]]
== `CREATE SEQUENCE`

.Назначение
Создание новой последовательности (генератора).
(((CREATE SEQUENCE))) (((CREATE GENERATOR)))

.Доступно в
DSQL, ESQL

.Синтаксис
[listing,subs=+quotes]
----
CREATE {SEQUENCE | GENERATOR} _seq_name_
[START WITH _start_value_] [INCREMENT [BY] _increment_]
----

[[fblangref-ddl-tbl-crtseq]]
.Параметры оператора `CREATE SEQUENCE`
[cols="<1,<3", options="header",stripes="none"]
|===
^| Параметр
^| Описание

|seq_name
|Имя последовательности (генератора). Может содержать до 63 символов.

|start_value
|Начальное значение последовательности (генератора).
По умолчанию равно `1`.

|increment
|Шаг приращения.
4 байтовое целое число.
По умолчанию равно `1`.
|===

Оператор `CREATE SEQUENCE` создаёт новую последовательность.
Слова `SEQUENCE` и `GENERATOR` являются синонимами.
Вы можете использовать любое из них, но рекомендуется использовать `SEQUENCE`.

(((CREATE SEQUENCE, STARTING WITH))) (((CREATE GENERATOR, STARTING WITH)))
В момент создания последовательности ей устанавливается значение, указанное в необязательном предложении `START WITH` минус значение приращения указанное в предложении `INCREMENT [BY]`. 
Если предложение `STARTING WITH` отсутствует, то последовательности устанавливается значение равное 1.
Таким образом, если начальное значение последовательности равно 100, а приращение 10, то первое значение выданное оператором `NEXT VALUE FOR` будет равно 100.

[NOTE]
====
До Firebird 4.0, первое значение выданное оператором `NEXT VALUE FOR` было равно 110.
====

(((CREATE SEQUENCE, INCREMENT BY))) (((CREATE GENERATOR, INCREMENT BY)))
Необязательное предложение `INCREMENT [BY]` позволяет задать шаг приращения для оператора `NEXT VALUES FOR`.
По умолчанию шаг приращения равен единице.
Приращение не может быть установлено в ноль для пользовательских последовательностей.
Значение последовательности изменяется также при обращении к функции `GEN_ID`, где в качестве параметра указывается имя последовательности и значение приращения, которое может быть отлично от указанного в предложении `INCREMENT BY`.

[[fblangref-ddl-sequence-create-who]]
=== Кто может создать последовательность?

Выполнить оператор `CREATE SEQUENCE` (`CREATE GENERATOR`) могут:

* <<fblangref-security-administrators,Администраторы>>
* Пользователи с привилегией `CREATE SEQUENCE` (`CREATE GENERATOR`).

Пользователь, создавший последовательность, становится её владельцем.

[[fblangref-ddl-sequence-create-examples]]
=== Примеры

.Создание последовательности
[example]
====
Создание последовательности EMP_NO_GEN с начальным значением 0 и шагом приращения равным единице.

[source,sql]
----
CREATE SEQUENCE EMP_NO_GEN;
----
====

.Создание последовательности
[example]
====
Создание последовательности EMP_NO_GEN с начальным значением 5 и шагом приращения равным единице.

[source,sql]
----
CREATE SEQUENCE EMP_NO_GEN START WITH 5;
----
====

.Создание последовательности
[example]
====
Создание последовательности EMP_NO_GEN с начальным значением 1 и шагом приращения равным 10.

[source,sql]
----
CREATE SEQUENCE EMP_NO_GEN INCREMENT BY 10;
----
====

.Создание последовательности
[example]
====
Создание последовательности EMP_NO_GEN с начальным значением 5 и шагом приращения равным 10.

[source,sql]
----
CREATE SEQUENCE EMP_NO_GEN START WITH 5 INCREMENT BY 10;
----
====

.См. также:
<<fblangref-ddl-sequence-alter,ALTER SEQUENCE>>, <<fblangref-ddl-sequence-setgen,SET GENERATOR>>, <<fblangref-ddl-sequence-drop,DROP SEQUENCE>>, <<fblangref-commons-nxtvlufor,NEXT VALUE FOR>>, <<fblangref-ddl-sequence-drop,GEN_ID>>.

[[fblangref-ddl-sequence-alter]]
== `ALTER SEQUENCE`

.Назначение
Изменение последовательности (генератора).
(((ALTER SEQUENCE))) (((ALTER GENERATOR)))

.Доступно в
DSQL, ESQL

.Синтаксис
[listing,subs=+quotes]
----
ALTER {SEQUENCE | GENERATOR} _seq_name_
[RESTART [WITH _newvalue_]]
[INCREMENT [BY] _increment_]
----

[[fblangref-ddl-tbl-alterseq]]
.Параметры оператора `ALTER SEQUENCE`
[cols="<1,<3", options="header",stripes="none"]
|===
^| Параметр
^| Описание

|seq_name
|Имя последовательности (генератора).

|newvalue
|Новое значение последовательности (генератора). 64 битное целое в диапазоне от -2^63^ до 2^63^ - 1

|increment
|Шаг приращения. Не может быть равным `0`.
|===

Оператор `ALTER SEQUENCE` устанавливает значение последовательности или генератора в заданное значение и/или изменяет значение приращения.

(((ALTER SEQUENCE, RESTART WITH))) (((ALTER GENERATOR, RESTART WITH)))
Предложение `RESTART WITH` позволяет установить значение последовательности.
(((ALTER SEQUENCE, RESTART))) (((ALTER GENERATOR, RESTART)))
Предложение `RESTART` может быть использовано самостоятельно (без `WITH`) для перезапуска значения последовательности с того значения с которого был начат старт генерации значений или предыдущий рестарт.

[WARNING]
====
Неосторожное использование оператора `ALTER SEQUENCE` (изменение значения последовательности или генератора) может привести к нарушению логической целостности данных.
====

(((ALTER SEQUENCE, INCREMENT BY))) (((ALTER GENERATOR, INCREMENT BY)))
Предложение `INCREMENT [BY]` позволяет изменить шаг приращения последовательности для оператора `NEXT VALUES FOR`.

[NOTE]
====
Изменение значения приращения -- это возможность, которая вступает в силу для каждого запроса, который запускается после фиксаций изменения.
Процедуры, которые вызваны впервые после изменения приращения, будут использовать новое значение, если они будут содержать операторы `NEXT VALUE FOR`.
Процедуры, которые уже работают, не будут затронуты, потому что они кэшируются.
Процедуры, использующие `NEXT VALUE FOR`, не должны быть перекомпилированы, чтобы видеть новое приращение, но если они уже работают или загружены, то никакого эффекта не будет.
Конечно процедуры, использующие `gen_id(_gen_, <expression>)`, не затронут при изменении приращения.
====

[[fblangref-ddl-sequence-alter-who]]
=== Кто может изменить последовательность?

Выполнить оператор `ALTER SEQUENCE` (`ALTER GENERATOR`) могут:

* <<fblangref-security-administrators,Администраторы>>
* Владелец последовательности (генератора); 
* Пользователи с привилегией `ALTER ANY SEQUENCE` (`ALTER ANY GENERATOR`).


[[fblangref-ddl-sequence-alter-examples]]
=== Примеры

.Изменение последовательности
[example]
====
Установка для последовательности EMP_NO_GEN значения 145.

[source,sql]
----
ALTER SEQUENCE EMP_NO_GEN RESTART WITH 145;
----
====

.Изменение последовательности
[example]
====
Сброс значения последовательности в то, которое было установлено при создании последовательности (или при предыдущей установке значения).

[source,sql]
----
ALTER SEQUENCE EMP_NO_GEN RESTART;
----
====

.Изменение последовательности
[example]
====
Изменение значения приращения последовательности EMP_NO_GEN.

[source,sql]
----
ALTER SEQUENCE EMP_NO_GEN INCREMENT BY 10;
----
====

.См. также:
<<fblangref-ddl-sequence-setgen,SET GENERATOR>>, <<fblangref-ddl-sequence-create,CREATE SEQUENCE>>, <<fblangref-ddl-sequence-drop,DROP SEQUENCE>>, <<fblangref-commons-nxtvlufor,NEXT VALUE FOR>>, <<fblangref-ddl-sequence-drop,GEN_ID>>.

[[fblangref-ddl-sequence-createoralter]]
== `CREATE OR ALTER SEQUENCE`

.Назначение
Создание новой или изменение существующей последовательности (генератора).
(((CREATE OR ALTER SEQUENCE))) (((CREATE OR ALTER GENERATOR)))

.Доступно в
DSQL, ESQL

.Синтаксис
[listing,subs=+quotes]
----
CREATE OR ALTER {SEQUENCE | GENERATOR} _seq_name_
[{START WITH _start_value_ | RESTART}]
[INCREMENT [BY] _increment_]
----

[[fblangref-ddl-sequence-crtoralt-tbl]]
.Параметры оператора `CREATE OR ALTER SEQUENCE`
[cols="<1,<3", options="header",stripes="none"]
|===
^| Параметр
^| Описание

|seq_name
|Имя последовательности (генератора). Может содержать до 63 символов.

|start_value
|Начальное значение последовательности (генератора).
По умолчанию равно `1`.

|increment
|Шаг приращения.
4 байтное целое число.
По умолчанию равно `1`.
|===

Если последовательности не существует, то она будет создана.
Уже существующая последовательность будет изменена, при этом существующие зависимости последовательности будут сохранены. 


[IMPORTANT]
====
Оператор CREATE OR ALTER SEQUENCE требует, чтобы хотя бы одно из необязательных предложений было указано.
====

[[fblangref-ddl-sequence-createoralter_examples]]
=== Примеры

.Создание новой или изменение существующей последовательности 
[example]
====
[source,sql]
----
CREATE OR ALTER SEQUENCE EMP_NO_GEN 
START WITH 10
INCREMENT BY 1;
----
====

.См. также:
<<fblangref-ddl-sequence-create,CREATE SEQUENCE>>, <<fblangref-ddl-sequence-alter,ALTER SEQUENCE>>, <<fblangref-ddl-sequence-setgen,SET GENERATOR>>. 

[[fblangref-ddl-sequence-drop]]
== `DROP SEQUENCE`

.Назначение
Удаление последовательности (генератора).
(((DROP SEQUENCE))) (((DROP GENERATOR)))

.Доступно в
DSQL, ESQL

.Синтаксис
[listing,subs=+quotes]
----
DROP {SEQUENCE | GENERATOR} _seq_name_
----

[[fblangref-ddl-tbl-dropseq]]
.Параметры оператора `DROP SEQUENCE`
[cols="<1,<3", options="header",stripes="none"]
|===
^| Параметр
^| Описание

|seq_name
|Имя последовательности (генератора).
|===

Оператор `DROP SEQUENCE` удаляет существующую последовательность (генератор). Слова `SEQUENCE` и `GENERATOR` являются синонимами.
Вы можете использовать любое из них, но рекомендуется использовать `SEQUENCE`.
При наличии зависимостей для существующей последовательности (генератора) удаления не будет выполнено. 

[[fblangref-ddl-sequence-drop_who]]
=== Кто может удалить генератор?

Выполнить оператор `DROP SEQUENCE` (`DROP GENERATOR`) могут:

* <<fblangref-security-administrators,Администраторы>>
* Владелец последовательности (генератора); 
* Пользователи с привилегией `DROP ANY SEQUENCE` (`DROP ANY GENERATOR`).


[[fblangref-ddl-sequence-drop_examples]]
=== Примеры

.Удаление последовательности 
[example]
====
[source,sql]
----
DROP SEQUENCE EMP_NO_GEN;
----
====

.См. также:
<<fblangref-ddl-sequence-create,CREATE SEQUENCE>>, <<fblangref-ddl-sequence-alter,ALTER SEQUENCE>>, <<fblangref-ddl-sequence-recreate,RECREATE SEQUENCE>>. 

[[fblangref-ddl-sequence-recreate]]
== `RECREATE SEQUENCE`

.Назначение
Создание или пересоздание последовательности (генератора).
(((RECREATE SEQUENCE))) (((RECREATE GENERATOR)))

.Доступно в
DSQL, ESQL

.Синтаксис
[listing,subs=+quotes]
----
RECREATE {SEQUENCE | GENERATOR} _seq_name_
  [START WITH _start_value_]
  [INCREMENT [BY] _increment_];
----

[[fblangref-ddl-sequence-recr-tbl]]
.Параметры оператора `RECREATE SEQUENCE`
[cols="<1,<3", options="header",stripes="none"]
|===
^| Параметр
^| Описание

|seq_name
|Имя последовательности (генератора). Может содержать до 63 символов.

|start_value
|Начальное значение последовательности (генератора).

|increment
|Шаг приращения.
4 байтное целое число.
|===

Оператор `RECREATE SEQUENCE` создаёт или пересоздаёт последовательность (генератор). Если последовательность с таким именем уже существует,
то оператор `RECREATE SEQUENCE` попытается удалить её и создать новую последовательность.
При наличии зависимостей для существующей последовательности оператор `RECREATE SEQUENCE` не выполнится.

[[fblangref-ddl-sequence-recreate-examples]]
=== Примеры

.Пересоздание последовательности 
[example]
====
[source,sql]
----
RECREATE SEQUENCE EMP_NO_GEN 
START WITH 10
INCREMENT BY 1;
----
====

[[fblangref-ddl-sequence-setgen]]
== `SET GENERATOR`

.Назначение
Устанавливает значение последовательности или генератора в заданное значение.
(((SET GENERATOR)))

.Доступно в
DSQL, ESQL

.Синтаксис
[listing,subs=+quotes]
----
SET GENERATOR _seq_name_ TO _new_val_
----

[[fblangref-ddl-tbl-setgen]]
.Параметры оператора `SET GENERATOR`
[cols="<1,<3", options="header",stripes="none"]
|===
^| Параметр
^| Описание

|seq_name
|Имя последовательности (генератора).

|new_val
|Новое значение последовательности (генератора). 64 битное целое в диапазоне от -2^63^ .. 2^63^ - 1
|===

Оператор `SET GENERATOR` устанавливает значение последовательности или генератора в заданное значение.

[NOTE]
====
Оператор `SET GENERATOR` считается устаревшим и оставлен ради обратной совместимости.
В настоящее время вместо него рекомендуется использовать стандарт-совместимый оператор `ALTER SEQUENCE`.

Неосторожное использование оператора `SET GENERATOR` (изменение значения последовательности или генератора) может привести к потере логической целостности данных.
====

[[fblangref-ddl-sequence-setgen-who]]
=== Кто может изменить значение генератора?

Выполнить оператор `SET GENERATOR` могут: 

* <<fblangref-security-administrators,Администраторы>>
* Владелец последовательности (генератора); 
* Пользователи с привилегией `ALTER ANY SEQUENCE` (`ALTER ANY GENERATOR`).


[[fblangref-ddl-sequence-setgen-examples]]
=== Примеры

.Установка значения для последовательности
[example]
====
[source,sql]
----
SET GENERATOR EMP_NO_GEN TO 145;
----
====

[NOTE]
====
То же самое можно сделать, используя оператор <<fblangref-ddl-sequence-alter,ALTER SEQUENCE>>

[source,sql]
----
ALTER SEQUENCE EMP_NO_GEN RESTART WITH 145;
----
====

.См. также:
<<fblangref-ddl-sequence-alter,ALTER SEQUENCE>>, <<fblangref-commons-nxtvlufor,NEXT VALUE FOR>>, <<fblangref-ddl-sequence-drop,GEN_ID>>.
