[[fblangref-intro]]
= О руководстве по языку SQL Firebird 4.0

Это руководство описывает язык SQL, поддерживаемый СУБД Firebird 4.0.

В руководстве также приводятся практические примеры использования SQL, многие из которых взяты из реальной практики.

[[fblangref-intro-subject]]
== Что содержит данный документ

Данный документ содержит описание языка SQL Firebird. Firebird полностью соответствует
международным стандартам SQL, от поддержки типов данных, структур хранения данных,
механизмов ссылочной целостности до возможностей управления данными и прав доступа.
В СУБД Firebird также реализован надежный процедурный язык — процедурный SQL (PSQL) — для
хранимых процедур, триггеров и динамически исполняемых блоков кода. Это те области, о
которых идет речь в этом руководстве.

В этом документе не рассматриваются вопросы конфигурация, инструменты командной
строки и описание API, и другое не относящееся к языку SQL.

[[fblangref-intro-authors]]
== Авторство

[[fblangref-intro-contributors]]
=== Авторы

[float]
==== Прямой контент

* Дмитрий Филиппов (писатель)
* Александр Карпейкин (писатель)
* Алексей Ковязин (писатель, редактор)
* Дмитрий Кузьменко (писатель, редактор)
* Денис Симонов (писатель, редактор)
* Paul Vinkenoog (писатель, дизайнер)
* Mark Rotteveel (писатель)

[float]
==== Ресурсы

* Дмитрий Еманов
* Adriano dos Santos Fernandes
* Александ Пешков
* Владислав Хорсун
* Claudio Valderrama
* Helen Borrie
* и другие

[[fblangref-acknowledgements]]
== Благодарности

[float]
[[_sponsors-donors]]
=== Спонсоры

Смотри список спонсоров Firebird 2.5 Language Reference.

[float]
[[_sponsors-native]]
==== Спонсоры Руководства по языку SQL на русском языке

[none]
* https://www.moex.com[Московская биржа]
+
Московская Биржа — крупнейший в России и Восточной Европе биржевой холдинг,
образованный 19 декабря 2011 года в результате слияния биржевых групп ММВБ (основана в
1992) и РТС (основана в 1995). Московская Биржа входит в двадцатку ведущих мировых
площадок по объёму торгов ценными бумагами, суммарной капитализации торгуемых акций и в
десятку крупнейших бирж производных финансовых инструментов.

* https://www.ib-aid.com[IBSurgeon] (https://ibase.ru[ibase.ru])
+
Техническая поддержка и инструменты
разработчика и администратора для СУБД Firebird.

[[fblangref-contributing]]

Есть несколько способов внести свой вклад в документацию Firebird или Firebird в целом:

* Участвуйте в списках рассылки (см. https://www.firebirdsql.org/en/mailing-lists/)
* Сообщайте об ошибках или отправляйте запросы на включение на GitHub (https://github.com/FirebirdSQL/)
* Станьте разработчиком (для документации свяжитесь с нами по firebird-docs, для Firebird в целом используйте список рассылки Firebird-devel)
* Пожертвуйте в Firebird Foundation (см. https://www.firebirdsql.org/en/donate/)
* Станьте платным членом или спонсором Firebird Foundation (см. https://www.firebirdsql.org/en/firebird-foundation/)

