
:sectnums!:

[appendix]
[[fblangref-montables]]
= Таблицы мониторинга

СУБД Firebird предоставляет возможность отслеживать работу с конкретной базой данных, выполняемую на стороне сервера.
Для этих целей используются таблицы мониторинга. Таблицы мониторинга имеют префикс имени `MON$`. Эти таблицы являются виртуальными в том смысле, что до обращения к ним со стороны пользователя, никаких данных в них не записано.
Они заполняются данными только в момент запроса пользователя (в том числе, поэтому на такие таблицы бесполезно пытаться создавать триггеры). При этом описания этих таблиц в базе данных присутствуют постоянно.

Ключевым понятием функции мониторинга является снимок активности.
Снимок представляет собой текущее состояние базы данных, содержащее множество информации о самой базе данных, активных соединениях, пользователях, транзакциях, подготовленных и выполняемых запросах и т.д.

Снимок создаётся при первой выборке из любой таблицы мониторинга и сохраняется до конца текущей транзакции, чтобы запросы к множеству таблиц (например, главная-подчинённая) всегда возвращал непротиворечивые данные.

Другими словами таблицы мониторинга ведут себя подобно `SNAPSHOT TABLE STABILITY` (`isc_tpb_consistency`) транзакции, даже если запросы к ним выполняются в транзакции с меньшим уровнем изолированности.

Для обновления снимка, текущая транзакция должна быть завершена и таблицы мониторинга должны быть запрошены в новом контексте транзакции.



.Безопасность:* Полный доступ ко всей информации, предоставляемой таблицами мониторинга, имеют SYSDBA и владелец базы данных;
* Обычные пользователи ограничены информацией о собственных соединениях, другие соединения невидимы для них.


[NOTE]
====
Частый сбор информации с помощью таблиц мониторинга в сильно нагруженной среде может негативно отразиться на производительности системы.
====

.Таблицы мониторинга

<<fblangref-montables-attachments,`MON$ATTACHMENTS`>>::
Сведения о текущих соединениях с базой данных.

<<fblangref-montables-call_stack,`MON$CALL_STACK`>>::
Обращения к стеку активными запросами хранимых процедур и
триггеров.

<<fblangref-montables-context_variables,`MON$CONTEXT_VARIABLES`>>::
Сведения о пользовательских контекстных переменных.

<<fblangref-montables-database,`MON$DATABASE`>>::
Сведения о базе данных, с которой выполнено соединение.

<<fblangref-montables-io_stats,`MON$IO_STATS`>>::
Статистика по вводу-выводу.

<<fblangref-montables-memory_usage,`MON$MEMORY_USAGE`>>::
Статистика использования памяти.

<<fblangref-montables-record_stats,`MON$RECORD_STATS`>>::
Статистика на уровне записей.

<<fblangref-montables-statements,`MON$STATEMENTS`>>::
Подготовленные к выполнению операторы.

<<fblangref-montables-table_stats,`MON$TABLE_STATS`>>::
Статистика на уровне таблиц.

<<fblangref-montables-transactions,`MON$TRANSACTIONS`>>::
Запущенные транзакции.


[[fblangref-montables-attachments]]
== `MON$ATTACHMENTS`

Сведения о текущих соединениях с базой данных.

.Описание столбцов таблицы `MON$ATTACHMENTS`
[cols="<4m,<3m,<5", frame="all", options="header",stripes="none"]
|===
^| Наименование столбца
^| Тип данных
^| Описание

|MON$ATTACHMENT_ID 
|BIGINT 
|Идентификатор соединения. 

|MON$SERVER_PID 
|INTEGER 
|Идентификатор серверного процесса. 

|MON$STATE 
|SMALLINT 
|Состояние соединения:

0 -- бездействующее; +
1 -- активное.

|MON$ATTACHMENT_NAME 
|VARCHAR(255) 
|Строка соединения -- полный путь к файлу и имя первичного файла
базы данных.

|MON$USER 
|CHAR(63) 
|Имя пользователя, соединённого с базой данных. 

|MON$ROLE 
|CHAR(63) 
|Имя роли, указанное при соединении. Если роль во время соединения
не была задана, поле содержит текст `NONE`.

|MON$REMOTE_PROTOCOL 
|VARCHAR(10) 
|Имя удалённого протокола. 

|MON$REMOTE_ADDRESS 
|VARCHAR(255) 
|Удалённый адрес (адрес и имя сервера). 

|MON$REMOTE_PID 
|INTEGER 
|Идентификатор удалённого клиентского процесса. 

|MON$CHARACTER_SET_ID 
|SMALLINT 
|Идентификатор набора символов в соединении. 

|MON$TIMESTAMP 
|TIMESTAMP 
|Дата и время начала соединения. 

|MON$GARBAGE_COLLECTION 
|SMALLINT 
|Флаг сборки мусора (указывается в DPB при подключении):
`1` - позволяется, `0` - не позволяется.

|MON$REMOTE_PROCESS 
|VARCHAR(255) 
|Полный путь к файлу и имя программного файла, выполнившего данное
соединение.

|MON$STAT_ID 
|INTEGER 
|Идентификатор статистики. 

|MON$CLIENT_VERSION 
|VARCHAR(255)
|Версия клиентской библиотеки.

|MON$REMOTE_VERSION 
|VARCHAR(255)
|Версия удалённого протокола.

|MON$REMOTE_HOST 
|VARCHAR(255)
|Имя удалённого хоста.

|MON$REMOTE_OS_USER 
|VARCHAR(255)
|Имя пользователя в операционной системе.

|MON$AUTH_METHOD 
|VARCHAR(255)
|Метод проверки подлинности, используемый при подключении.

|MON$SYSTEM_FLAG 
|SMALLINT
|Флаг того, что подключение системное:

`0` -- пользовательское подключение; +
`1` -- системное подключение.

|MON$IDLE_TIMEOUT
|INTEGER
|Тайм-аут простоя соединения уровня соединения. Содержит значение
тайм-аута простоя уровня соединения, в секундах. Если тайм-аут не
установлен -- `0`.

|MON$IDLE_TIMER
|TIMESTAMP
|Время истечения таймера ожидания. Содержит `NULL`, если тайм-аут
простоя соединения не установлен, или если таймер не запущен.

|MON$STATEMENT_TIMEOUT
|INTEGER
|Тайм-аут SQL оператора уровня соединения. Содержит значение
тайм-аута, установленное на уровне соединения, в миллисекундах. Если
тайм-аут не установлен -- `0`.

|MON$WIRE_COMPRESSED
|BOOLEAN
|Используется ли сжатие сетевого трафика. Если используется сжатие
сетевого трафика значение равно `TRUE`, если не используется -- `FALSE`.
Для встроенных соединений -- возвращает `NULL`.

|MON$WIRE_ENCRYPTED
|BOOLEAN
|Используется ли шифрование сетевого трафика. Если используется
шифрование сетевого трафика значение равно `TRUE`, если не
используется -- `FALSE`. Для встроенных соединений -- возвращает `NULL`.

|MON$WIRE_CRYPT_PLUGIN
|CHAR(63) 
|Имя текущего плагина для шифрования сетевого трафика, если оно
используется, в противном случае `NULL`.
|===

.Примеры:


.Получение сведений о клиентских приложениях
[example]
====
[source,sql]
----
SELECT MON$USER, MON$REMOTE_ADDRESS, MON$REMOTE_PID, MON$TIMESTAMP
FROM MON$ATTACHMENTS
WHERE MON$ATTACHMENT_ID <> CURRENT_CONNECTION
----
====

[[fblangref-montables-attachments_delete]]
=== Использование MON$ATTACHMENTS для закрытия подключений

Таблицы мониторинга доступны только для чтения.
Однако в сервер встроен механизм для удаления (и только удаления) записей в таблице `MON$ATTACHMENTS`, что позволяет, закрыть соединение с базой данных.

[NOTE]
====
* Вся текущая активность в удаляемом соединении немедленно прекращается, и все активные транзакции откатываются (триггеры на события `ON DISCONNECT` и `ON TRANSACTION ROLLBACK` не вызываются);
* Закрытое соединение вернёт приложению ошибку с кодом `isc_att_shutdown`;
* Последующие попытки использовать это соединение (т.е. использовать его handle в API-вызовах) вернут ошибки;
* Завершение системных соединений (`MON$SYSTEM_FLAG = 1`) невозможно. Сервер пропустит системные подключения затронутые оператором `DELETE FROM MON$ATTACHMENTS`.
====


.Отключение всех соединений, за исключением своего
[example]
====
[source,sql]
----
DELETE FROM MON$ATTACHMENTS
WHERE MON$ATTACHMENT_ID <> CURRENT_CONNECTION
----
====

[[fblangref-montables-call_stack]]
== `MON$CALL_STACK`

Обращения к стеку запросами хранимых процедур, хранимых функций и триггеров.

.Описание столбцов таблицы `MON$CALL_STACK`
[cols="<4m,<3m,<5", frame="all", options="header",stripes="none"]
|===
^| Наименование столбца
^| Тип данных
^| Описание

|MON$CALL_ID 
|BIGINT 
|Идентификатор обращения. 

|MON$STATEMENT_ID 
|BIGINT 
|Идентификатор верхнего уровня оператора SQL -- оператора,
инициировавшего цепочку обращений. По этому идентификатору можно
найти запись об активном операторе в таблице `MON$STATEMENTS`.

|MON$CALLER_ID 
|BIGINT 
|Идентификатор обращающегося триггера, хранимой функции или
хранимой процедуры.

|MON$OBJECT_NAME 
|CHAR(63) 
|Имя объекта PSQL. 

|MON$OBJECT_TYPE 
|SMALLINT 
|Тип объекта PSQL:

`2` -- триггер; +
`5` -- хранимая процедура; +
`15` -- хранимая функция.

|MON$TIMESTAMP 
|TIMESTAMP 
|Дата и время старта обращения. 

|MON$SOURCE_LINE 
|INTEGER 
|Номер исходной строки оператора SQL, выполняющегося в настоящий
момент.

|MON$SOURCE_COLUMN 
|INTEGER 
|Номер исходного столбца оператора SQL, выполняющегося в настоящий
момент.

|MON$STAT_ID 
|INTEGER 
|Идентификатор статистики. 

|MON$PACKAGE_NAME
|CHAR(63) 
|Имя пакета для упакованных процедур/функций.
|===

[NOTE]
====
В стек вызовов не попадёт информация о вызовах при выполнении оператора `EXECUTE STATEMENT`.
====


.Получение стека вызовов для всех подключений кроме своего
[example]
====
[source,sql]
----
WITH RECURSIVE
  HEAD AS (
    SELECT 
      CALL.MON$STATEMENT_ID, CALL.MON$CALL_ID, 
      CALL.MON$OBJECT_NAME, CALL.MON$OBJECT_TYPE
    FROM MON$CALL_STACK CALL
    WHERE CALL.MON$CALLER_ID IS NULL
    UNION ALL
    SELECT 
      CALL.MON$STATEMENT_ID, CALL.MON$CALL_ID, 
      CALL.MON$OBJECT_NAME, CALL.MON$OBJECT_TYPE
    FROM MON$CALL_STACK CALL
      JOIN HEAD ON CALL.MON$CALLER_ID = HEAD.MON$CALL_ID
  )
SELECT MON$ATTACHMENT_ID, MON$OBJECT_NAME, MON$OBJECT_TYPE
FROM HEAD
  JOIN MON$STATEMENTS STMT ON STMT.MON$STATEMENT_ID = HEAD.MON$STATEMENT_ID
WHERE STMT.MON$ATTACHMENT_ID <> CURRENT_CONNECTION
----
====

[[fblangref-montables-context_variables]]
== `MON$CONTEXT_VARIABLES`

Сведения о пользовательских контекстных переменных.

.Описание столбцов таблицы `MON$CONTEXT_VARIABLES`
[cols="<4m,<3m,<5", frame="all", options="header",stripes="none"]
|===
^| Наименование столбца
^| Тип данных
^| Описание

|MON$ATTACHMENT_ID 
|BIGINT 
|Идентификатор соединения. Содержит корректное значение только для
контекстных переменных уровня соединения, для переменных уровня
транзакции устанавливается в `NULL`.

|MON$TRANSACTION_ID 
|BIGINT
|Идентификатор транзакции. Содержит корректное значение только для
контекстных переменных уровня транзакции, для переменных уровня
соединения устанавливается в `NULL`.

|MON$VARIABLE_NAME 
|VARCHAR(80) 
|Имя контекстной переменной. 

|MON$VARIABLE_VALUE 
|VARCHAR(32765) 
|Значение контекстной переменной. 
|===

.Получение всех сессионных контекстных переменных для текущего подключения
[example]
====
[source,sql]
----
SELECT VAR.MON$VARIABLE_NAME, VAR.MON$VARIABLE_VALUE
FROM MON$CONTEXT_VARIABLES VAR
WHERE VAR.MON$ATTACHMENT_ID = CURRENT_CONNECTION
----
====

[[fblangref-montables-database]]
== `MON$DATABASE`

Сведения о базе данных, с которой выполнено соединение.

.Описание столбцов таблицы `MON$DATABASE`
[cols="<4m,<3m,<5", frame="all", options="header",stripes="none"]
|===
^| Наименование столбца
^| Тип данных
^| Описание

|MON$DATABASE_NAME 
|VARCHAR(255) 
|Полный путь и имя первичного файла базы данных или псевдоним базы
данных.

|MON$PAGE_SIZE 
|SMALLINT 
|Размер страницы файлов базы данных в байтах. 

|MON$ODS_MAJOR 
|SMALLINT 
|Старшая версия ODS. 

|MON$ODS_MINOR 
|SMALLINT 
|Младшая версия ODS. 

|MON$OLDEST_TRANSACTION 
|BIGINT 
|Номер старейшей заинтересованной транзакции -- OIT, Oldest
Interesting Transaction.

|MON$OLDEST_ACTIVE 
|BIGINT 
|Номер старейшей активной транзакции -- OAT, Oldest Active
Transaction.

|MON$OLDEST_SNAPSHOT 
|BIGINT 
|Номер транзакции, которая была активной на момент старта
транзакции OAT, транзакция OST -- Oldest Snapshot Transaction.

|MON$NEXT_TRANSACTION 
|BIGINT 
|Номер следующей транзакции. 

|MON$PAGE_BUFFERS 
|INTEGER 
|Количество страниц, выделенных в оперативной памяти для кэша. 

|MON$SQL_DIALECT 
|SMALLINT 
|SQL диалект базы данных: 1 или 3. 

|MON$SHUTDOWN_MODE 
|SMALLINT 
|Текущее состояние останова (shutdown) базы данных:

0 -- база данных активна (online); +
1 -- останов для нескольких пользователей (multi-user shutdown); +
2 -- останов для одного пользователя (single-user shutdown); +
3 -- полный останов (full shutdown).


|MON$SWEEP_INTERVAL 
|INTEGER 
|Интервал чистки (sweep interval).

|MON$READ_ONLY 
|SMALLINT 
|Признак, является база данных только для чтения, read only,
(значение `1`) или для чтения и записи, read-write (`0`).

|MON$FORCED_WRITES 
|SMALLINT 
|Указывает, установлен ли для базы режим синхронного вывода
(forced writes, значение `1`) или режим асинхронного вывода (значение `0`).

|MON$RESERVE_SPACE 
|SMALLINT 
|Флаг, указывающий на резервирование пространства.

|MON$CREATION_DATE 
|TIMESTAMP 
|Дата и время создания базы данных.

|MON$PAGES 
|BIGINT 
|Количество страниц, выделенных для базы данных на внешнем
устройстве.

|MON$STAT_ID 
|INTEGER 
|Идентификатор статистики.

|MON$BACKUP_STATE 
|SMALLINT 
|Текущее физическое состояние backup:

 `0` -- нормальное; +
 `1` -- заблокированное; +
 `2` -- слияние (объединение).

|MON$CRYPT_STATE
|SMALLINT
|Текущее состояние шифрования:

`0` -- не зашифрована; +
`1` -- зашифрована; +
`2` -- в процессе дешифрования; +
`3` -- в процессе шифрования.

|MON$CRYPT_PAGE
|BIGINT 
|Количество зашифрованных/дешифрованных страниц в процессе
шифрования/дешифрования; ноль если этот процесс закончился или не
начинался.

|MON$OWNER
|CHAR(63) 
|Владелец базы данных.

|MON$SEC_DATABASE 
|CHAR(7)
|Отображает, какой тип базы данных безопасности используется:

`Default` -- база данных безопасности по умолчанию, т.е. [path]_security4.fdb_; +
`Self` -- в качестве базы данных безопасности используется текущая база данных; +
`Other` -- в качестве базы данных безопасности используется другая база данных (не сама и не [path]_security4.fdb_).


|MON$GUID
|CHAR(38)
|GUID базы данных.

|MON$FILE_ID
|VARCHAR(255)
|Уникальный идентификатор базы данных на уровне файловой
системы.

|MON$NEXT_ATTACHMENT
|BIGINT
|Номер (идентификатор) следующего соединения.

|MON$NEXT_STATEMENT
|BIGINT
|Номер (идентификатор) следующего SQL запроса.

|MON$REPLICA_MODE
|SMALLINT
|Режим репликации:

`0` - `NONE` -- база данных является первичной; +
`1` - `READ-ONLY` -- реплика в режиме только чтение; +
`2` - `READ-WRITE` -- реплика в режиме чтение и запись.

|===

[[fblangref-montables-io_stats]]
== `MON$IO_STATS`

Статистика по вводу-выводу.

.Описание столбцов таблицы `MON$IO_STATS`
[cols="<4m,<3m,<5", frame="all", options="header",stripes="none"]
|===
^| Наименование столбца
^| Тип данных
^| Описание

|MON$STAT_ID 
|INTEGER 
|Идентификатор статистики. 

|MON$STAT_GROUP 
|SMALLINT 
|Группа статистики:

`0` -- база данных (database); +
`1` -- соединение с базой данных (connection); +
`2` -- транзакция (transaction); +
`3` -- оператор (statement); +
`4` -- вызов (call).


|MON$PAGE_READS 
|BIGINT 
|Количество прочитанных (read) страниц базы данных. 

|MON$PAGE_WRITES 
|BIGINT 
|Количество записанных (write) страниц базы данных. 

|MON$PAGE_FETCHES 
|BIGINT 
|Количество загруженных в память (fetch) страниц базы данных. 

|MON$PAGE_MARKS 
|BIGINT 
|Количество отмеченных (mark) страниц базы данных. 
|===

Счётчики этой таблицы являются накопительными и накапливают информацию по каждой из групп статистики.

[[fblangref-montables-memory_usage]]
== `MON$MEMORY_USAGE`

Статистика использования памяти.

.Описание столбцов таблицы `MON$MEMORY_USAGE`
[cols="<4m,<3m,<5", frame="all", options="header",stripes="none"]
|===
^| Наименование столбца
^| Тип данных
^| Описание

|MON$STAT_ID 
|INTEGER 
|Идентификатор статистики. 

|MON$STAT_GROUP 
|SMALLINT 
|Группа статистики:

`0` -- база данных (database); +
`1` -- соединение с базой данных (connection); +
`2` -- транзакция (transaction); +
`3` -- оператор (statement); +
`4` -- вызов (call).


|MON$MEMORY_USED 
|BIGINT 
|
Количество используемой памяти, байт.
Информация о высокоуровневом распределении памяти, выполненной сервером из пулов.
Может быть полезна для отслеживания утечек памяти и чрезмерного потребления памяти в соединениях, процедурах и т.д.

|MON$MEMORY_ALLOCATED 
|BIGINT 
|

Количество памяти, выделенной ОС, байт.
Информация о низкоуровневом распределении памяти, выполненном менеджером памяти Firebird -- объем памяти, выделенный операционной системой, что позволяет контролировать физическое потребление памяти.
Обратите внимание, не все записи этого столбца имеют ненулевые значения.
Малые выделения памяти здесь не фиксируются, а вместо этого добавляются к пулу памяти базы данных.
Только `MON$DATABASE` (`MON$STAT_GROUP = 0`) и связанные с выделением памяти объекты имеют ненулевое значение.

|MON$MAX_MEMORY_USED 
|BIGINT 
|Максимальное количество байт, используемое данным
объектом.

|MON$MAX_MEMORY_ALLOCATED 
|BIGINT 
|Максимальное количество байт, выделенное ОС данному
объекту.
|===

[NOTE]
====
Счётчики, связанные с записями уровня базы данных `MON$DATABASE` (`MON$STAT_GROUP = 0`), отображают выделение памяти для всех соединений.
В архитектурах Classic и SuperClassic нулевые значения счётчиков обозначают, что в этих архитектурах нет общего кэша. 
====

.Получение 10 запросов потребляющих наибольшее количество памяти
[example]
====
[source,sql]
----
SELECT STMT.MON$ATTACHMENT_ID, STMT.MON$SQL_TEXT, MEM.MON$MEMORY_USED
FROM MON$MEMORY_USAGE MEM
   NATURAL JOIN MON$STATEMENTS STMT
ORDER BY MEM.MON$MEMORY_USED DESC 
FETCH FIRST 10 ROWS ONLY
----
====

[[fblangref-montables-record_stats]]
== `MON$RECORD_STATS`

Статистика на уровне записей.

.Описание столбцов таблицы `MON$RECORD_STATS`
[cols="<4m,<3m,<5", frame="all", options="header",stripes="none"]
|===
^| Наименование столбца
^| Тип данных
^| Описание

|MON$STAT_ID 
|INTEGER 
|Идентификатор статистики. 

|MON$STAT_GROUP 
|SMALLINT 
|Группа статистики:

`0` -- база данных (database); +
`1` -- соединение с базой данных (connection); +
`2` -- транзакция (transaction); +
`3` -- оператор (statement); +
`4` -- вызов (call).

|MON$RECORD_SEQ_READS 
|BIGINT 
|Количество последовательно считанных записей (read sequentially). 

|MON$RECORD_IDX_READS 
|BIGINT 
|Количество записей, прочитанных при помощи индекса (read via an index).

|MON$RECORD_INSERTS 
|BIGINT 
|Количество добавленных записей (inserted records). 

|MON$RECORD_UPDATES 
|BIGINT 
|Количество изменённых записей (updated records). 

|MON$RECORD_DELETES 
|BIGINT 
|Количество удалённых записей (deleted records). 

|MON$RECORD_BACKOUTS 
|BIGINT 
|Количество возвращённых в базу данных записей (backed out
                                records). 

|MON$RECORD_PURGES 
|BIGINT 
|Количество удалённых ненужных записей (purged records). 

|MON$RECORD_EXPUNGES 
|BIGINT 
|Количество вычищенных средствами сборки мусора записей (expunged records).

|MON$RECORD_LOCKS 
|BIGINT 
|Количество записей прочитанных с использованием предложения `WITH LOCK`.

|MON$RECORD_WAITS 
|BIGINT 
|Количество попыток обновления/модификации/блокировки записей
принадлежащих нескольким активным транзакциям. Транзакция находится
в режиме `WAIT`.

|MON$RECORD_CONFLICTS 
|BIGINT 
|Количество неудачных попыток обновления/модификации/блокировки
записей принадлежащих нескольким активным транзакциям. В таких
ситуациях сообщается о конфликте обновления (`UPDATE CONFLICT`).

|MON$BACKVERSION_READS 
|BIGINT 
|Количество прочитанных версий при поиске видимых версий записей.

|MON$FRAGMENT_READS 
|BIGINT 
|Количество прочитанных фрагментов записей. 

|MON$RECORD_RPT_READS 
|BIGINT 
|Количество повторно прочитанных записей. 

|MON$RECORD_IMGC
|BIGINT
|Количество записей вычищенных промежуточной сборкой мусора.
|===

Счётчики этой таблицы являются накопительными и накапливают информацию по каждой из групп статистики.

[[fblangref-montables-statements]]
== `MON$STATEMENTS`

Подготовленные к выполнению операторы.

.Описание столбцов таблицы `MON$STATEMENTS`
[cols="<4m,<3m,<5", frame="all", options="header",stripes="none"]
|===
^| Наименование столбца
^| Тип данных
^| Описание

|MON$STATEMENT_ID 
|BIGINT 
|Идентификатор оператора. 

|MON$ATTACHMENT_ID 
|BIGINT 
|Идентификатор соединения. 

|MON$TRANSACTION_ID 
|BIGINT 
|Идентификатор транзакции. 

|MON$STATE 
|SMALLINT 
|Состояние оператора:

`0` -- бездействующий (idle); +
`1` -- выполняемый (active); +
`2` -- приостановленный (stalled).


|MON$TIMESTAMP 
|TIMESTAMP 
|Дата и время старта оператора. 

|MON$SQL_TEXT 
|BLOB TEXT 
|Текст оператора на языке SQL. 

|MON$STAT_ID 
|INTEGER 
|Идентификатор статистики. 

|MON$EXPLAINED_PLAN 
|BLOB TEXT 
|План оператора в explain форме. 

|MON$STATEMENT_TIMEOUT
|INTEGER
|Тайм-аут SQL оператора уровня SQL оператора. Содержит значение
тайм-аута, установленное на уровне соединения/оператора, в
миллисекундах. Если тайм-аут не установлен -- `0`.

|MON$STATEMENT_TIMER
|TIMESTAMP
|Время истечения таймера SQL оператора. Содержит `NULL`, если
тайм-аут SQL оператора не установлен, или если таймер не
запущен.
|===

Состояние оператора `STALLED` -- это состояние "`приостановлено`". Возможно для запроса, который начал своё выполнение, ещё не завершил его, но в данный момент не выполняется.
Например, ждёт входных параметров или очередного фетча (fetch) от клиента.


.Отображение активных запросов за исключением тех, что выполняются в своём соединении
[example]
====
[source,sql]
----
SELECT ATT.MON$USER, ATT.MON$REMOTE_ADDRESS, STMT.MON$SQL_TEXT, STMT.MON$TIMESTAMP
FROM MON$ATTACHMENTS ATT
  JOIN MON$STATEMENTS STMT ON ATT.MON$ATTACHMENT_ID = STMT.MON$ATTACHMENT_ID
WHERE ATT.MON$ATTACHMENT_ID <> CURRENT_CONNECTION
  AND STMT.MON$STATE = 1
----
====

[[fblangref-montables-statements_delete]]
=== Использование `MON$STATEMENTS` для отмены запросов

Таблицы мониторинга доступны только для чтения.
Однако в сервер встроен механизм для удаления (и только удаления) записей в таблице `MON$STATEMENTS`, что позволяет завершить активный запрос.

[NOTE]
====
* Попытка отмены запросов не выполняется, если в соединении в настоящее время нет никаких выполняющихся операторов.
* После отмены запроса вызов API-функций execute/fetch вернёт ошибку с кодом `isc_cancelled`.
* Последующие запросы в данном соединении не запрещены.
* Отмена запроса не происходит синхронно, оператор лишь помечает запрос на отмену, а сама отмена производится ядром асинхронно.
====

.Отмена всех активных запросов для заданного соединения
[example]
====
[source,sql]
----
DELETE FROM MON$STATEMENTS
WHERE MON$ATTACHMENT_ID = 32
----
====

[[fblangref-montables-table_stats]]
== `MON$TABLE_STATS`

Статистика на уровне таблицы.

.Описание столбцов таблицы `MON$TABLE_STATS`
[cols="<4m,<3m,<5", frame="all", options="header",stripes="none"]
|===
^| Наименование столбца
^| Тип данных
^| Описание

|MON$STAT_ID 
|INTEGER 
|Идентификатор статистики. 

|MON$STAT_GROUP 
|SMALLINT 
|Группа статистики:

`0` -- база данных (database); +
`1` -- соединение с базой данных (connection); +
`2` -- транзакция (transaction); +
`3` -- оператор (statement); +
`4` -- вызов (call).


|MON$TABLE_NAME 
|CHAR(63) 
|Имя таблицы. 

|MON$RECORD_STAT_ID 
|INTEGER 
|Ссылка на MON$RECORD_STATS. 
|===


.Получение статистики на уровне записей по каждой таблицы для своего соединения
[example]
====
[source,sql]
----
SELECT
    t.mon$table_name,
    r.mon$record_inserts,
    r.mon$record_updates,
    r.mon$record_deletes,
    r.mon$record_backouts,
    r.mon$record_purges,
    r.mon$record_expunges,
    ------------------------
    r.mon$record_seq_reads,
    r.mon$record_idx_reads,
    r.mon$record_rpt_reads,
    r.mon$backversion_reads,
    r.mon$fragment_reads,
    ------------------------
    r.mon$record_locks,
    r.mon$record_waits,
    r.mon$record_conflicts,
    ------------------------
    a.mon$stat_id
FROM
    mon$record_stats r
    JOIN mon$table_stats t ON r.mon$stat_id = t.mon$record_stat_id
    JOIN mon$attachments a ON t.mon$stat_id = a.mon$stat_id
WHERE
      a.mon$attachment_id = CURRENT_CONNECTION
----
====

[[fblangref-montables-transactions]]
== `MON$TRANSACTIONS`

Описывает начатые транзакции

.Описание столбцов таблицы `MON$TRANSACTIONS`
[cols="<4m,<3m,<5", frame="all", options="header",stripes="none"]
|===
^| Наименование столбца
^| Тип данных
^| Описание

|MON$TRANSACTION_ID 
|BIGINT 
|Идентификатор (номер) транзакции. 

|MON$ATTACHMENT_ID 
|BIGINT 
|Идентификатор соединения. 

|MON$STATE 
|SMALLINT 
|Состояние транзакции:

`0` -- бездействующая (транзакция не имеет связанных с ней запросов); +
`1` -- активная (есть хотя бы один запрос связанный с транзакцией).

Запрос связывается с транзакцией, когда начинает его выполнение.
Эта связь разрывается, когда запрос начинает новое выполнение в другой транзакции, или, когда транзакция или запрос удаляется, но не тогда, когда запрос выполнен или из курсора выбраны все записи.

|MON$TIMESTAMP 
|TIMESTAMP 
|Дата и время старта транзакции. 

|MON$TOP_TRANSACTION 
|INTEGER 
|Верхний предел используемый транзакцией чистильщика (sweeper) при
продвижении глобального OIT. Все транзакции выше этого порога
считаются активными. Обычно он эквивалентен `MON$TRANSACTION_ID`, но
использование `COMMIT RETAINING` или `ROLLBACK RETAINING` приводит к
тому, что `MON$TOP_TRANSACTION` останется неизменным ("`зависшим`") при
увеличении идентификатора транзакции.

|MON$OLDEST_TRANSACTION 
|INTEGER 
|Номер старейшей заинтересованной транзакции -- OIT, Oldest
Interesting Transaction.

|MON$OLDEST_ACTIVE 
|INTEGER 
|Номер старейшей активной транзакции -- OAT, Oldest Active
Transaction.

|MON$ISOLATION_MODE 
|SMALLINT 
|Режим (уровень) изоляции:

`0` -- consistency (snapshot table stability); +
`1` -- concurrency (snapshot); +
`2` -- read committed record version; +
`3` -- read committed no record version; +
`4` -- read committed read consistency.


|MON$LOCK_TIMEOUT 
|SMALLINT 
|Время ожидания:

`-1` -- бесконечное ожидание (wait); +
`0` -- транзакция no wait; +
другое число -- время ожидания в секундах (lock timeout).


|MON$READ_ONLY 
|SMALLINT 
|Признак, является ли транзакцией только для чтения, read only
(значение `1`) или для чтения и записи, read-write (`0`).

|MON$AUTO_COMMIT 
|SMALLINT 
|Признак, используется ли автоматическое подтверждение транзакции
auto-commit (значение `1`) или нет (`0`).

|MON$AUTO_UNDO 
|SMALLINT 
|Признак, используется ли автоматическая отмена транзакции
auto-undo (значение `1`) или нет (`0`). Если используется автоматическая
отмена транзакции, создаётся точка сохранения уровня транзакции.
Существование точки сохранения позволяет отменять изменения, если
вызывается `ROLLBACK`, после чего транзакция просто фиксируется. Если
этой точки сохранения не существует или она существует, но
количество изменений очень велико, выполняется фактический `ROLLBACK`,
и транзакция помечается в TIP как «мертвая».

|MON$STAT_ID 
|INTEGER 
|Идентификатор статистики. 
|===


.Получение всех подключений, которые стартовали Read Write транзакции с уровнем изоляции выше Read Committed.
[example]
====
[source,sql]
----
SELECT
    DISTINCT a.*
FROM
    mon$attachments a
    JOIN mon$transactions t ON a.mon$attachment_id = t.mon$attachment_id
WHERE
  NOT(t.mon$read_only = 1 AND t.mon$isolation_mode >= 2);
----
====

:sectnums:

