:sectnums!:

[appendix]
[[fblangref-limits]]
= Ограничения Firebird

[[fblangref-appx09-tbl-limits]]
.Ограничения Firebird
[cols="<1,<2", options="header",stripes="none"]
|===
| Пункт
| Значение

|Максимальный размер базы данных
|128 TB (`2^32^ * _page_size_`)

|Максимальное количество таблиц
|32768

|Максимальный размер одной таблицы
|~18 TB

|Максимальный размер файла внешней таблицы (EXTERNAL TABLE)
|Неограничен

|Максимальное количество записей в таблице
|`< 2^40^`

|Максимальный размер записи таблицы
|64 KB

|Максимальный размер страницы
|32 KB

2+|*Замечание*: Допустимые размеры страницы: 4096, 8192, 16384, 32768.

|Максимальное количество столбцов в таблице
|Зависит от типов столбцов (их размера). +
`max_row_size / total_column_size`

2+|*Замечание*: BLOB и массивы хранятся по ссылке. Идентификатор BLOB занимает 8-байт. Размер самих BLOB и массивов не учитывается в размере записи.

|Максимальный размер ключа индекса
|~ 8 KB (1/4 размера страницы)

|Максимальное количество столбцов в композитном индексе
|16

|Максимальный идентификатор транзакции
|48-бит (~ `2.8 * 10^14^`)

2+|*Замечание*: Когда будет достигнут максимальный лимит идентификаторов транзакций, базу данных необходимо пометить как доступную только для чтения, и выполнить резервное копирование и восстановление с помощью `gbak`.

|Максимальное количество форматов метаданных таблицы
|255

2+|См. <<fblangref-ddl-table-alter-versinc>>

|Максимальный размер SQL запроса
|~ 10 MB (по соображениям безопасности)

|Максимальное количество BLR контекстов
|255

|===

== Что такое BLR контекст?

При компиляции SQL запросы и хранимые модули (процедуры, функции, триггеры) преобразуют код на языке SQL в более компактное промежуточное представление называемое BLR (Binary Language Representation). Для хранимых модулей этот BLR сохраняется и затем используется движком. Для DSQL запросов SQL преобразуется в BLR при подготовке (компиляции) запроса.

Во время выполнения запрос вычисляет и хранит состояние каждого потока данных (в простейшем случае таблицы). Операторы BLR принимают номера потоков (контекстов) как параметры. Номер контекста кодируется 1 байтом, отсюда ограничение на количество контекстов, равное 255.

Ограничение на количество BLR контекстов не позволяет создавать SQL запросы или хранимые процедуры с большим количеством потоков данных. Например вы не можете написать SQL запрос с более 255 соединениями таблиц (такое редко надо). Однако в некоторых случаях, ограничение на количество BLR контекстов мешает писать большие хранимые процедуры или `EXECUTE BLOCK`.

Рассмотрим следующий пример:

[source,sql]
----
EXECUTE BLOCK
AS
BEGIN
  INSERT INTO T(A) VALUES(1);
  INSERT INTO T(A) VALUES(2);
  -- ...
  INSERT INTO T(A) VALUES(255);
END
----

В данном случае ограничение на количество BLR контекстов не даст вам использовать `INSERT INTO T ...` более 255 раз.

[IMPORTANT]
====
Выполнение `INSERT INTO T` в цикле с параметрами использует один контекст, и не зависит от количества итераций.

Каждый хранимый модуль имеет свой счётчик BLR контекстов. Вызов из процедуры другой процедуры это один контекст. Таким образом, внутренние контексты вызываемой процедуры не добавляются к счётчику BLR контекстов текущего уровня.
====

:sectnums:
