
[[fblangref-ddl-database]]
= DATABASE

В данном разделе описываются вопросы создания базы данных, подключения к существующей базе данных, изменения структуры файлов, перевод базы данных в состояние, необходимое для безопасного резервного копирования, и обратно и удаления базы данных. 

[[fblangref-ddl-database-create]]
== `CREATE DATABASE`

.Назначение
Создание новой базы данных.
(((CREATE DATABASE)))

.Доступно в
DSQL, ESQL

[[fblangref-ddl-db-create-syntax]]
.Синтаксис
[listing,subs="+quotes,attributes"]
----
CREATE {DATABASE | SCHEMA} <filespec>
  [<db_initial_option> [<db_initial_option> ...]]
  [<db_config_option> [<db_config_option> ...]]

<db_initial_option> ::=
    USER _username_
  | PASSWORD '_password_'
  | ROLE _rolename_
  | PAGE_SIZE [=] _size_
  | LENGTH [=] _num_ [PAGE[S]]
  | SET NAMES '_charset_'

<db_config_option> ::=
    DEFAULT CHARACTER SET _default_charset_
      [COLLATION _collation_]
  | <sec_file>
  | DIFFERENCE FILE '_diff_file_'


<filespec> ::= '[<server_spec>]{_filepath_ | _db_alias_}'

<server_spec> ::= 
    _host_[/ {_port_ | _service_}]:
  | {backslash}{backslash}__host__\
  | <protocol>://[_host_[:{_port_ | _service_}]/]

<protocol> ::= inet | inet4 | inet6 | wnet | xnet

<sec_file> ::=
  FILE '_filepath_'
  [LENGTH [=] _num_ [PAGE[S]]
  [STARTING [AT [PAGE]] _pagenum_]
----

[NOTE]
====
Каждый _db_initial_option_ и _db_config_option_ может встречаться не более одного раза, за исключением _sec_file_, который может встречаться ноль или более раз.
====

.Параметры оператора `CREATE DATABASE`
[[fblangref-ddl-tbl-createdatabase]]
[cols="<1,<3", options="header",stripes="none"]
|===
^|Параметр
^|Описание

|filespec
|Спецификация первичного файла базы данных.

|server_spec
|Спецификация удалённого сервера.
Включает в себя имя сервера и протокол.
Необходима, если база данных создаётся на удалённом сервере.

|filepath
|Полный путь и имя файла, включая расширение.
Имя файла должно быть задано в соответствии со спецификой используемой платформы.

|db_alias
|Псевдоним (alias) базы данных, присутствующий в файле [path]_databases.conf_

|host
|Имя сервера или IP адрес, на котором создаётся база данных.

|port
|Номер порта, который слушает удалённый сервер (параметр [parameter]``RemoteServicePort`` файла [path]_firebird.conf_).

|service
|Имя сервиса.
Должно совпадать со значением параметра [parameter]``RemoteServiceName`` файла [path]_firebird.conf_.

|protocol
|Наименование протокола.

|username
|Имя пользователя-владельца базы данных.
Может быть заключено в одинарные или двойные кавычки.
Если имя пользователя заключено в двойные кавычки, то оно чувствительно к регистру.

|password
|Пароль пользователя-владельца базы данных.
Чувствительно к регистру.

|role
|Имя роли, права которой могут учитываться при создании базы данных.
Может быть заключено в одинарные или двойные кавычки.
Если имя роли заключено в двойные кавычки, то оно чувствительно к регистру.

|size
|Размер страницы для базы данных.
Допустимые значения 4096, 8192, 16384, 32768.
Размер страницы по умолчанию 8192.

|num
|Максимальный размер первичного или вторичного файла в страницах.

|charset
|Задаёт набор символов подключения, доступного после успешного создания базы данных.

|default_charset
|Задаёт набор символов по умолчанию для строковых типов данных.

|collation
|Сортировка для набора символов по умолчанию.

|sec_file
|Спецификация вторичного файла.

|pagenum
|Номер страницы, с которой начинается вторичный файл базы данных.

|diff_file
|Путь и имя дельта файла.
|===

Оператор `CREATE DATABASE` создаёт новую базу данных.
Вы можете использовать `CREATE DATABASE` или `CREATE SCHEMA`.
Это синонимы. 

База данных может состоять из одного или нескольких файлов.
Первый, основной, файл называется первичным, остальные файлы -- вторичными. 

[NOTE]
====
В настоящее время многофайловые базы данных являются атавизмом.
Многофайловые базы данных имеет смысл использовать на старых файловых системах, в которых существует ограничение на размер любого файла.
Например, в FAT32 нельзя создать файл больше 4-х гигабайт.
====

Спецификация первичного файла -- имя файла базы данных и его расширение с указанием к нему полного пути в соответствии с правилами используемой операционной системы.
При создании базы данных файл базы данных должен отсутствовать.
В противном случае будет выдано сообщение об ошибке и база данных не будет создана.
Если полный путь к базе данных не указан, то база данных будет создана в одном из системных каталогов.
В каком именно зависит от операционной системы. 

[[fblangref-ddl-database-create-aliasedb]]
=== Использование псевдонимов БД

Вместо полного пути к первичному файлу базы можно использовать псевдонимы (aliases). Псевдонимы описываются в файле [path]_databases.conf_ в формате:

[listing,subs=+quotes]
----
_alias_ = _filepath_
----

[NOTE]
====
Помимо указания псевдонимов для базы данных в этом файле можно задать параметры уровня базы данных для каждой описываемой базы данных.
Эти параметры задаются в фигурных скобках сразу после объявления псевдонима.
====

[[fblangref-ddl-database-create-remotely]]
=== Создание БД на удалённом сервере

При создании базы данных на удалённом сервере необходимо указать спецификацию удалённого сервера.
Спецификация удалённого сервера зависит от используемого протокола. 

Если вы при создании базы данных используете протокол TCP/IP, то спецификация первичного файла должна выглядеть следующим образом:

[listing,subs=+quotes]
----
_host_[/{_port_ | _service_}]:{_filepath_ | _db_alias_}
----

Если вы при создании базы данных используете протокол под названием именованные каналы (Name Pipes), то спецификация первичного файла должна выглядеть следующим образом.

[listing,subs="+quotes,attributes"]
----
{backslash}{backslash}__host__\{_filepath_ | _db_alias_}
----

Существует также унифицированный URL-подобный синтаксис спецификации удалённого сервера.
В этом синтаксисе первым параметром указывается наименование протокола, далее указывается имя сервера или IP адрес, номер порта и путь к первичному файлу базы данных или псевдоним.
В качестве протокола можно указать следующие значения:

INET:: TCP/IP (сначала пробует подключиться по протоколу TCP/IP v6, если не получилось, то TCP/IP v4);
INET4:: TCP/IP v4;
INET6:: TCP/IP v6;
WNET:: протокол именованных каналов (Named Pipes);
XNET:: локальный протокол.

[listing,subs=+quotes]
----
<protocol>://[_host_[:{_port_ | _service_}]/]{_filepath_ | _db_alias_}
----

[[fblangref-ddl-database-create-optionals]]
=== Необязательные параметры `CREATE DATABASE`

`USER` и `PASSWORD`::
(((CREATE DATABASE, USER))) (((CREATE DATABASE, PASSWORD)))
Необязательные предложения `USER` и `PASSWORD` задают, соответственно, имя и пароль пользователя присутствующего в базе данных безопасности ([path]_security4.fdb_ или той, что указана в параметре [parameter]``SecurityDatabase``). Пользователя и пароль можно не указывать, если установлены переменные окружения [var]``ISC_USER`` и [var]``ISC_PASSWORD``.
Пользователь, указанный при создании базы данных, будет её владельцем.

`ROLE`::
(((CREATE DATABASE, ROLE)))
Необязательное предложение `ROLE` задаёт имя роли (обычно это `RDB$ADMIN`), права которой будут учитываться при создании базы данных.
Роль должна быть назначена пользователю в соответствующей базе данных безопасности.

`PAGE_SIZE`::
(((CREATE DATABASE, PAGE_SIZE)))
Необязательное предложение `PAGE_SIZE` задаёт размер страницы базы данных.
Этот размер будет установлен для первичного файла и всех вторичных файлов базы данных.
При вводе размера страницы БД меньшего, чем 4096, он будет автоматически изменён на 4096.
Другие числа (не равные 4096, 8192, 16384 или 32768) будут изменены на ближайшее меньшее из поддерживаемых значений.
Если размер страницы базы данных не указан, то по умолчанию принимается значение 8192. 

.Больше не значит лучше
[TIP]
====
Большие размеры страницы могут вместить больше записей на одной странице, иметь более широкие индексы и больше индексов, но они также будут тратить больше места для BLOB (сравните потраченное впустую пространство BLOB размером 3 КБ на странице размером 4096 и такого же BLOB на 32768: +/- 1 КБ против +/- 29 КБ). Кроме того, при большом размере страницы увеличивается конкуренция за одну и ту же страницу данных, поскольку на неё вмещается больше записей, который могли бы располагаться на разных страницах. 
====

`LENGTH`::
(((CREATE DATABASE, LENGTH)))
Необязательное предложение `LENGTH` задаёт максимальный размер первичного или вторичного файла базы данных в страницах.
При создании базы данных её первичный или вторичный файл будут занимать минимально необходимое количество страниц для хранения системных данных, не зависимо от величины, установленной в предложении `LENGHT`.
Для единственного или последнего (в многофайловой базе данных) файла значение `LENGTH` никак не влияет на его размер.
Файл будет автоматически увеличивать свой размер по мере необходимости.

`SET NAMES`::
(((CREATE DATABASE, SET NAMES)))
Необязательное предложение `SET NAMES` задаёт набор символов подключения, доступного после успешного создания базы данных.
По умолчанию используется набор символов NONE.

`DEFAULT CHARACTER SET`::
(((CREATE DATABASE, DEFAULT CHARACTER SET)))
Необязательное предложение `DEFAULT CHARACTER SET` задаёт набор символов по умолчанию для строковых типов данных.
Наборы символов применяются для типов `CHAR`, `VARCHAR` и `BLOB`.
По умолчанию используется набор символов `NONE`.
Для набора символов по умолчанию можно также указать сортировку по умолчанию (`COLLATION`). В этом случае сортировка станет умалчиваемой для набора символов по умолчанию (т.е.
для всей БД за исключением случаев использования других наборов символов).

`STARTING AT`::
(((CREATE DATABASE, STARTING AT)))
Предложение `STARTING AT` задаёт номер страницы базы данных, с которой должен начинаться следующий файл базы данных.
Когда предыдущий файл будет полностью заполнен данными в соответствии с заданным номером страницы, система начнёт помещать вновь добавляемые данные в следующий файл базы данных.

`DIFFERENCE FILE`::
(((CREATE DATABASE, DIFFERENCE FILE)))
Необязательное предложение `DIFFERENCE FILE` задаёт путь и имя дельта файла, в который будут записываться изменения, внесённые в БД после перевода её в режим "`безопасного копирования`" ("`copy-safe`") путём выполнения команды `ALTER DATABASE BEGIN BACKUP`.
Полное описание данного параметра см.
в <<fblangref-ddl-database-alter,`ALTER DATABASE`>>.

[[fblangref-ddl-db-create-dialect]]
=== Диалект базы данных

По умолчанию база данных создаётся в 3 диалекте.
Для того чтобы база данных была создана в нужном вам диалекте SQL, следует перед выполнением оператора создания базы данных задать нужный диалект, выполнив оператор `SET SQL DIALECT`.

[[fblangref-ddl-database-create-who]]
=== Кто может создать базу данных?

Выполнить оператор `CREATE DATABASE` могут:

* <<fblangref-security-administrators,Администраторы>>;
* Пользователи с привилегией `CREATE DATABASE`.


[[fblangref-ddl-database-create-examples]]
=== Примеры

.Создание базы данных в операционной системе Windows
[example]
====
Создание базы данных в операционной системе Windows расположенной на диске D с размером страницы 8192.
Владельцем базы данных будет пользователь wizard.
База данных будет в 1 диалекте, и использовать набор символов по умолчанию WIN1251.

[source,sql]
----
SET SQL DIALECT 1;
CREATE DATABASE 'D:\test.fdb'
USER wizard PASSWORD 'player' ROLE RDB$ADMIN
DEFAULT CHARACTER SET WIN1251;
----
====

.Создание базы данных в операционной системе Linux
[example]
====
Создание базы данных в операционной системе Linux с размером страницы 4096.
Владельцем базы данных будет пользователь wizard.
База данных будет в 3 диалекте, и использовать набор символов по умолчанию UTF8 с умалчиваемой сортировкой `UNICODE_CI_AI`.

[source,sql]
----
CREATE DATABASE '/home/firebird/test.fdb'
USER "wizard" PASSWORD 'player' ROLE 'RDB$ADMIN'
PAGE_SIZE = 4096
DEFAULT CHARACTER SET UTF8 COLLATION UNICODE_CI_AI;
----
====

[IMPORTANT]
====
В данном случае при создании базы данных будет учитываться регистр символов для имени пользователя, потому что оно указано в двойных кавычках.
====

.Создание базы данных на удалённом сервере
[example]
====
Создание базы данных на удалённом сервере baseserver расположенном по пути, на который ссылается псевдоним test, описанный в файле [path]_databases.conf_.
Используется протокол TCP.
Владельцем базы данных будет пользователь wizard.

[source,sql]
----
CREATE DATABASE 'baseserver:test'
USER wizard PASSWORD 'player' ROLE RDB$ADMIN
DEFAULT CHARACTER SET UTF8;
----

То же самое с использованием унифицированного URL-подобного синтаксиса задания спецификации удалённого сервера.

[source,sql]
----
CREATE DATABASE 'inet://baseserver:3050/test'
USER wizard PASSWORD 'player' ROLE RDB$ADMIN
DEFAULT CHARACTER SET UTF8;
----

или

[source,sql]
----
CREATE DATABASE 'inet://baseserver:gds_db/test'
USER wizard PASSWORD 'player' ROLE RDB$ADMIN
DEFAULT CHARACTER SET UTF8;
----

При использовании доменных имён может быть полезно указать какой именно из протоколов IP v4 или IP v6 вы хотите использовать.

[source,sql]
----
CREATE DATABASE 'inet4://baseserver/test'
USER wizard PASSWORD 'player' ROLE RDB$ADMIN
DEFAULT CHARACTER SET UTF8;
----

или

[source,sql]
----
CREATE DATABASE 'inet6://baseserver/test'
USER wizard PASSWORD 'player' ROLE RDB$ADMIN
DEFAULT CHARACTER SET UTF8;
----

Создание базы данных с указанием IP адреса (IPv4) вместо указания имени сервера.

[source,sql]
----
CREATE DATABASE '127:0:0:1:test'
USER wizard PASSWORD 'player' ROLE RDB$ADMIN
DEFAULT CHARACTER SET UTF8;
----

Создание базы данных с указанием IP адреса (IPv6) вместо указания имени сервера.

[source,sql]
----
CREATE DATABASE '[::1]:test'
USER wizard PASSWORD 'player' ROLE RDB$ADMIN
DEFAULT CHARACTER SET UTF8;
----
====

.Создание многофайловой базы данных
[example]
====
Создание базы данных в 3 диалекте с набором символов по умолчанию UTF8.
Первичный файл будет содержать 10000 страниц с размером страницы 8192.
Как только в процессе работы с базой данных первичный файл будет заполнен, СУБД будет помещать новые данные во вторичный файл [path]_test.fdb2_.
Аналогичные действия будут происходить и со вторым вторичным файлом.
Размер последнего файла будет увеличиваться до тех пор, пока это позволяет используемая операционная система или пока не будет исчерпана память на внешнем носителе.

[source,sql]
----
SET SQL DIALECT 3;
CREATE DATABASE 'baseserver:D:\test.fdb'
USER wizard PASSWORD 'player' ROLE 'RDB$ADMIN'
PAGE_SIZE = 8192
DEFAULT CHARACTER SET UTF8
FILE 'D:\test.fdb2'
STARTING AT PAGE 10001
FILE 'D:\test.fdb3'
STARTING AT PAGE 20001;
----
====

.Создание многофайловой базы данных 2
[example]
====
Создание базы данных в 3 диалекте с набором символов по умолчанию UTF8.
Первичный файл будет содержать 10000 страниц с размером страницы 8192.
Как только в процессе работы с базой данных первичный файл будет заполнен, СУБД будет помещать новые данные во вторичный файл [path]_test.fdb2_.
Аналогичные действия будут происходить и со вторым вторичным файлом.

[source,sql]
----
SET SQL DIALECT 3;
CREATE DATABASE 'baseserver:D:\test.fdb'
USER wizard PASSWORD 'player' ROLE 'RDB$ADMIN'
PAGE_SIZE = 8192
LENGTH 10000 PAGES
DEFAULT CHARACTER SET UTF8
FILE 'D:\test.fdb2'
FILE 'D:\test.fdb3'
STARTING AT PAGE 20001;
----
====

.См. также:
<<fblangref-ddl-database-alter>>, <<fblangref-ddl-database-drop>>.

[[fblangref-ddl-database-alter]]
== `ALTER DATABASE`

.Назначение
Изменение структуры файлов базы данных, переключение её в состояние "`безопасное для копирования`" или изменение некоторых свойств базы данных.
(((ALTER DATABASE)))

.Доступно в
DSQL, ESQL

.Синтаксис
[listing,subs=+quotes]
----
ALTER {DATABASE | SCHEMA}
    {<add_sec_clause> [<add_sec_clausee> ...]}
  | {ADD DIFFERENCE FILE '_diff_file_' | DROP DIFFERENCE FILE}
  | {{BEGIN | END} BACKUP}
  | {SET DEFAULT CHARACTER SET _charset_}
  | {SET DEFAULT SQL SECURITY {DEFINER | INVOKER}}
  | {SET LINGER TO _linger_duration_ | DROP LINGER}
  | {ENCRYPT WITH _plugin_name_ [KEY _key_name_] | DECRYPT}
  | {ENABLE | DISABLE} PUBLICATION
  | INCLUDE {TABLE <table_list> | ALL} TO PUBLICATION
  | EXCLUDE {TABLE <table_list> | ALL} FROM PUBLICATION

<add_sec_clause> ::= ADD <sec_file> [<sec_file> ...]

<sec_file> ::=
  FILE '_filepath_'
  [STARTING [AT [PAGE]] _pagenum_]
  [LENGTH [=] _num_ [PAGE[S]]
                        
<table_list> ::= _tablename_ [, _tablename_ ...]
----

[[fblangref-ddl-tbl-alterdatabase]]
.Параметры оператора `ALTER DATABASE`
[cols="<1,<3", options="header",stripes="none"]
|===
^|Параметр
^|Описание

|add_sec_clause
|Инструкция для добавления вторичного файла базы данных.

|sec_file
|Спецификация вторичного файла.

|filepath
|Полный путь и имя дельта файла или вторичного файла базы данных.

|pagenum
|Номер страницы, с которой начинается вторичный файл базы данных.

|num
|Максимальный размер вторичного файла в страницах.

|diff_file
|Путь и имя дельта файла.

|charset
|Новый набор символов по умолчанию для базы данных.

|linger_duration
|Задержка в секундах.

|plugin_name
|Имя плагина шифрования.

|key_name
|Имя ключа шифрования.

|table_list
|Список таблиц, которые необходим разрешить или запретить для
публикации (репликации).

|tablename
|Имя таблицы.
|===

Оператор `ALTER DATABASE` изменяет структуру файлов базы данных или переключает её в состояние "`безопасное для копирования`". 

[[fblangref-ddl-database-alter-addfile]]
=== Добавление вторичного файла

(((ALTER DATABASE, ADD FILE)))
Предложение `ADD FILE` добавляет к базе данных вторичный файл.
Для вторичного файла необходимо указывать полный путь к файлу и имя вторичного файла.
Описание вторичного файла аналогично тому, что описано в операторе CREATE DATABASE. 

.Добавление вторичного файла в базу данных
[example]
====
Как только в предыдущем первичном или вторичных файлах будет заполнено 30000 страниц, СУБД будет помещать данные во вторичный файл [path]_test4.fdb_.

[source,sql]
----
ALTER DATABASE 
ADD FILE 'D:\test.fdb4'
STARTING PAGE 30001;
----
====

[[fblangref-ddl-database-alter-add-diffile]]
=== Изменение пути и имени дельта файла

(((ALTER DATABASE, ADD DIFFERENCE FILE)))
Предложение `ADD DIFFERENCE FILE` задаёт путь и имя дельта файла, в который будут записываться изменения, внесённые в базу данных после перевода её в режим "`безопасного копирования`" ("`copy-safe`"). Этот оператор в действительности не добавляет файла.
Он просто переопределяет умалчиваемые имя и путь файла дельты.
Для изменения существующих установок необходимо сначала удалить ранее указанное описание файла дельты с помощью оператора DROP DIFFERENCE FILE, а затем задать новое описание файла дельты.
Если не переопределять путь и имя файла дельты, то он будет иметь тот же путь и имя, что и БД, но с расширением [path]_.delta_. 

[NOTE]
====
При задании относительного пути или только имени файла дельты он будет создаваться в текущем каталоге сервера.
Для операционных систем Windows это системный каталог. 
====

(((ALTER DATABASE, DROP DIFFERENCE FILE)))
Предложение `DROP DIFFERENCE FILE` удаляет описание (путь и имя) файла дельты, заданное ранее командой `ADD DIFFERENCE FILE`.
На самом деле при выполнении этого оператора файл не удаляется.
Он удаляет путь и имя файла дельты и при последующем переводе БД в режим "`безопасного копирования`" будут использованы значения по умолчанию (т.е.
тот же путь и имя, что и у файла БД, но с расширением [path]_.delta_).

.Установка пути и имени файла дельты
[example]
====
[source,sql]
----
ALTER DATABASE 
ADD DIFFERENCE FILE 'D:\test.diff';
----
====

.Удаление описание файла дельты
[example]
====
[source,sql]
----
ALTER DATABASE 
DROP DIFFERENCE FILE;
----
====

[[fblangref-ddl-database-alter-backup]]
=== Перевод базы данных в режим "`безопасного копирования`"

(((ALTER DATABASE, BEGIN BACKUP)))
Предложение `BEGIN BACKUP` предназначено для перевода базы данных в режим "`безопасного копирования`" ("`copy-safe`"). Этот оператор "`замораживает`" основной файл базы данных, что позволяет безопасно делать резервную копию средствами файловой системы, даже если пользователи подключены и выполняют операции с данными.
При этом все изменения, вносимые пользователями в базу данных, будут записаны в отдельный файл, так называемый дельта файл (__delta file__). 

[NOTE]
====
Оператор `BEGIN BACKUP`, несмотря на синтаксис, не начинает резервное копирование базы данных, а лишь создаёт условия для его осуществления.
====

(((ALTER DATABASE, END BACKUP)))
Предложение `END BACKUP` предназначено для перевода базы данных из режима "`безопасного копирования`" ("`copy-safe`") в режим нормального функционирования.
Этот оператор объединяет файл дельты с основным файлом базы данных и восстанавливает нормальное состояние работы, таким образом, закрывая возможность создания безопасных резервных копий средствами файловой системы.
(При этом безопасное резервное копирование с помощью утилиты [app]``gbak`` остаётся доступным). 

.Перевод базы данных в режим "`безопасного копирования`"
[example]
====
[source,sql]
----
ALTER DATABASE 
BEGIN BACKUP;
----
====

.Возвращение базы данных в режим нормального функционирования из режима "`безопасного копирования`"
[example]
====
[source,sql]
----
ALTER DATABASE 
END BACKUP;
----
====

[[fblangref-ddl-database-alter-charset]]
=== Изменение набора символов по умолчанию

(((ALTER DATABASE, SET DEFAULT CHARACTER SET)))
Предложение `SET DEFAULT CHARACTER SET` изменяет набор символов по умолчанию для базы данных.
Это изменение не затрагивает существующие данные.
Новый набор символов по умолчанию будет использоваться только в последующих DDL командах, кроме того для них будет использоваться сортировка по умолчанию для нового набора символов.


.Изменение набора символов по умолчанию для базы данных
[example]
====
[source,sql]
----
ALTER DATABASE SET DEFAULT CHARACTER SET WIN1251;
----
====

[[fblangref-ddl-database-alter-sql-security]]
=== Изменение привилегий выполнения по умолчанию

(((ALTER DATABASE, SET DEFAULT SQL SECURITY)))
Начиная с Firebird 4.0 появилась возможность указывать объектам метаданных с какими привилегиями они будут выполняться: вызывающего или определяющего пользователя.
Для этого используется предложение `SQL SECURITY`, которое можно указать для таблицы, триггера, процедуры, функции или пакета.
Если выбрана опция `INVOKER`, то объект метаданных будет выполняться с привилегиями вызывающего пользователя.
Если выбрана опция `DEFINER`, то объект метаданных будет выполняться с привилегиями определяющего пользователя (владельца). Если при создании PSQL модуля или таблицы предложение `SQL SECURITY` не задано, то по умолчанию используется опция INVOKER.

Предложение `SET DEFAULT SQL SECURITY` изменяет привилегии выполнения с которым по умолчанию выполняются PSQL модули (хранимые процедуры, функции и пакеты).

.Изменение привилегий выполнения по умолчанию
[example]
====
После выполнения данного оператора PSQL модули по умолчанию будут выполняться с опцией `SQL SECURITY DEFINER`


[source,sql]
----
ALTER DATABASE SET DEFAULT SQL SECURITY DEFINER;
----
====

[[fblangref-ddl-database-alter-linger]]
=== `LINGER`

(((ALTER DATABASE, SET LINGER)))
Предложение `SET LINGER` позволяет установить задержку закрытия базы данных.
Этот механизм позволяет Firebird в режиме SuperServer, сохранять базу данных в открытом состоянии в течение некоторого времени после того как последние соединение закрыто, т.е.
иметь механизм задержки закрытия базы данных.
Это может помочь улучшить производительность и уменьшить издержки в случаях, когда база данных часто открывается и закрывается, сохраняя при этом ресурсы "`разогретыми`" до следующего открытия. 

[TIP]
====
Такой режим может быть полезен для Web приложений, в которых коннект к базе обычно "`живёт`" очень короткое время. 
====

(((ALTER DATABASE, DROP LINGER)))
Предложение `DROP LINGER` удаляет задержку и возвращает базу данных к нормальному состоянию (без задержки). Эта команда эквивалентна установки задержки в 0. 

[TIP]
====
Удаление `LINGER` не самое лучшее решение для временной необходимости его отключения для некоторых разовых действий, требующих принудительного завершения работы сервера.
Утилита [app]``gfix`` теперь имеет переключатель [option]``-NoLinger``, который сразу закроет указанную базу данных, после того как последнего соединения не стало, независимо от установок LINGER в базе данных.
Установка `LINGER` будет сохранена и нормально отработает в следующий раз.

Кроме того, одноразовое переопределение доступно также через сервисы API, с использованием тега isc_spb_prp_nolinger, например (в такой строке): 


[source]
----
fbsvcmgr host:service_mgr user sysdba password xxx
action_properties dbname employee prp_nolinger
----
====


.Установка задержки в 30 секунд
[example]
====
[source,sql]
----
ALTER DATABASE SET LINGER 30;
----
====

.Удаление задержки
[example]
====
[source,sql]
----
ALTER DATABASE DROP LINGER;
----

или

[source,sql]
----
ALTER DATABASE SET LINGER 0;
----
====

[[fblangref-ddl-database-alter-encrypt]]
=== Шифрование базы данных

(((ALTER DATABASE, ENCRYPT WITH)))
Оператор `ALTER DATABASE` с предложением `ENCRYPT WITH` шифрует базу данных с помощью указанного плагина шифрования.
Шифрование начинается сразу после этого оператора и будет выполняться в фоновом режиме.
Нормальная работа с базами данных не нарушается во время шифрования. 

[NOTE]
====
Процесс шифрования может быть проконтролирован с помощью поля `MON$CRYPT_PAGE` в псевдо-таблице `MON$DATABASE` или просмотрен на странице заголовка базы данных с помощью `gstat -e`.

`gstat –h` также будет предоставлять ограниченную информацию о состоянии шифрования. 

Например, следующий запрос

[source,sql]
----
select MON$CRYPT_PAGE * 100 / MON$PAGES from MON$DATABASE
----

будет отображать процент завершения процесса шифрования.
====

Необязательное предложение `KEY` позволяет передать имя ключа для плагина шифрования.
Что делать с этим именем ключа решает плагин.

(((ALTER DATABASE, DECRYPT)))
Оператор `ALTER DATABASE` с предложением `DECRYPT` дешифрует базу данных.

.Шифрование базы данных
[example]
====
[source,sql]
----
ALTER DATABASE ENCRYPT WITH DbCrypt;
----
====

.Дешифрование базы данных
====
[example]
[source,sql]
----
ALTER DATABASE DECRYPT;
----
====

[[fblangref-ddl-database-alter-publication]]
=== Управление репликацией

(((ALTER DATABASE, ENABLE PUBLICATION)))
Оператор `ALTER DATABASE` с предложением `ENABLE PUBLICATION` включает репликацию базы данных.

[source,sql]
----
ALTER DATABASE ENABLE PUBLICATION
----

(((ALTER DATABASE, DISABLE PUBLICATION)))
Для отключения репликации базы данных выполните оператор

[source,sql]
----
ALTER DATABASE DISABLE PUBLICATION
----

Изменения будут применены сразу после подтверждения транзакции.

(((ALTER DATABASE, `INCLUDE ... TO PUBLICATION`)))
При настойке репликации должен быть определен набор репликации (он же публикация). Он включает в себя таблицы, которые должны быть реплицированы.
Это также делается с помощью команды DDL:

[listing,subs=+quotes]
----
ALTER DATABASE INCLUDE {TABLE <table_list> | ALL} TO PUBLICATION

<table_list> ::= _tablename_ [, _tablename_ ...]
----

(((ALTER DATABASE, `INCLUDE ... TO PUBLICATION`, ALL)))
При использовании ключевого слова `ALL` в набор репликации будут включены все таблицы, включая те что будут созданы позднее.
Команда будет выглядеть следующим образом:

[source,sql]
----
ALTER DATABASE INCLUDE ALL TO PUBLICATION
----

(((ALTER DATABASE, `INCLUDE ... TO PUBLICATION`, TABLE)))
Вы можете задать конкретный набор таблиц для репликации.
Для этого после ключевого слова `TABLE` необходимо указать список таблиц через запятую.
В следующем примере мы разрешаем репликацию для таблиц t1 и t2:

[source,sql]
----
ALTER DATABASE INCLUDE TABLE t1, t2 TO PUBLICATION
----

(((ALTER DATABASE, `EXCLUDE ... FROM PUBLICATION`)))
Для исключения таблиц из набора репликации (публикации) используется следующий оператор:

[listing,subs=+quotes]
----
ALTER DATABASE EXCLUDE {TABLE <table_list> | ALL} FROM PUBLICATION

<table_list> ::= _tablename_ [, _tablename_ ...]
----

(((ALTER DATABASE, `EXCLUDE ... FROM PUBLICATION`, ALL)))
При использовании ключевого слова `ALL` из набора репликации будут исключены все таблицы.
Если ранее в публикацию были добавлены все таблицы с использованием ключевого слова ALL, то данный оператор отключит автоматическую публикацию для вновь создаваемых таблиц.
Команда будет выглядеть следующим образом:

[source,sql]
----
ALTER DATABASE EXCLUDE ALL FROM PUBLICATION
----

(((ALTER DATABASE, `EXCLUDE ... FROM PUBLICATION`, TABLE)))
Вы можете задать конкретный набор таблиц для исключения из репликации.
Для этого после ключевого слова TABLE необходимо указать список таблиц через запятую.
В следующем примере мы исключаем таблицы t1 и t2 из набора репликации:

[source,sql]
----
ALTER DATABASE EXCLUDE TABLE t1, t2 FROM PUBLICATION
----

Таблицы, включенные для репликации, могут быть дополнительно отфильтрованы с использованием двух параметров в файле конфигурации [path]_replication.conf_: [parameter]``include_filter`` и [parameter]``exclude_filter``.
Это регулярные выражения, которые применяются к именам таблиц и определяют правила для включения таблиц в набор репликации или исключения их из набора репликации.

[[fblangref-ddl-database-alter-who]]
=== Кто может выполнить `ALTER DATABASE`?

Выполнить оператор `ALTER DATABASE` могут: 

* <<fblangref-security-administrators,Администраторы>>;
* Владелец базы данных; 
* Пользователи с привилегией `ALTER DATABASE`.


.См. также:
<<fblangref-ddl-database-create,CREATE DATABASE>>, <<fblangref-ddl-database-drop,DROP DATABASE>>.

[[fblangref-ddl-database-drop]]
== `DROP DATABASE`

.Назначение
Удаление текущей базы данных.
(((DROP DATABASE)))

.Доступно в
DSQL, ESQL

.Синтаксис
[listing,subs]
----
DROP DATABASE
----

Оператор `DROP DATABASE` удаляет текущую базу данных.
Перед удалением базы данных, к ней необходимо присоединиться.
Оператор удаляет первичный, все вторичные файлы и все файлы теневых копий. 

[[fblangref-ddl-database-drop-who]]
=== Кто может удалить базу данных?

Выполнить оператор `DROP DATABASE` могут: 

* <<fblangref-security-administrators,Администраторы>>;
* Владелец базы данных; 
* Пользователи с привилегией `DROP DATABASE`.


[[fblangref-ddl-database-drop-examples]]
=== Примеры

.Удаление базы данных
[example]
====
Удаление базы данных, к которой подключен клиент.

[source,sql]
----
DROP DATABASE;
----
====

.См. также:
<<fblangref-ddl-database-create,CREATE DATABASE>>, <<fblangref-ddl-database-alter,ALTER DATABASE>>.

